<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dml="http://www.eclipselabs.org/damos/DML/1.0.0" xmlns:dmlnotation="http://www.eclipselabs.org/damos/DMLNotation/1.0.0" xmlns:module="http://www.wisag.de/Automation/Micas/Module" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation">
  <module:Module xmi:id="_mWhzsO0OEeGWI9AsFWcjow" processor="m_calmbach" examiner="m_calmbach" createdDate="2012-08-23T12:37:55.691+0200" lastModifiedDate="2012-08-23T12:37:55.691+0200" lastInstallDate="2012-08-23T12:37:55.691+0200" name="aC40 Module 02">
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HMLoO0OEeGWI9AsFWcjow" name="0002-032-00-C-ZW" dataType="Reference" description="ZE 1" row="32" column="0"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HREIO0OEeGWI9AsFWcjow" name="0002-007-00-C-MW" dataType="Reference" description="ME 5" row="7" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HSSQO0OEeGWI9AsFWcjow" name="0002-000-09-C-1D" dataType="Reference" description="" column="9" referenceType="FgaMessageConst"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HS5UO0OEeGWI9AsFWcjow" name="0002-034-00-C-AW" dataType="Reference" description="" row="34" column="0" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HTgYO0OEeGWI9AsFWcjow" name="0002-000-08-C-BM" dataType="Reference" description="" column="8" referenceType="FgaMessageConst"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HUugO0OEeGWI9AsFWcjow" name="0002-021-00-C-AW" dataType="Reference" description="AS 6" row="18" column="0" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HVVkO0OEeGWI9AsFWcjow" name="0002-011-00-C-MW" dataType="Reference" description="ME 9" row="11" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HV8oO0OEeGWI9AsFWcjow" name="0002-005-00-C-MW" dataType="Reference" description="ME 3" row="5" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HWjsO0OEeGWI9AsFWcjow" name="0002-000-05-C-1D" dataType="Reference" description="" column="5" referenceType="FgaMessageConst"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HY_8O0OEeGWI9AsFWcjow" name="0002-021-00-C-MW" dataType="Reference" description="" row="21" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HaOEO0OEeGWI9AsFWcjow" name="0002-004-00-C-MW" dataType="Reference" description="ME 2" row="4" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1Ha1IO0OEeGWI9AsFWcjow" name="0002-029-00-C-MW" dataType="Reference" description="" row="29" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HcDQO0OEeGWI9AsFWcjow" name="0002-025-00-C-MW" dataType="Reference" description="" row="25" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HcqUO0OEeGWI9AsFWcjow" name="0002-010-00-C-MW" dataType="Reference" description="ME 8" row="10" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1Hd4cO0OEeGWI9AsFWcjow" name="0002-001-09-C-1D" dataType="Reference" description="" row="1" column="9" referenceType="FgaMessageConst"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HefgO0OEeGWI9AsFWcjow" name="0002-028-00-C-MW" dataType="Reference" description="" row="28" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HftoO0OEeGWI9AsFWcjow" name="0002-024-00-C-MW" dataType="Reference" description="" row="24" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1Hg7wO0OEeGWI9AsFWcjow" name="0002-006-00-C-MW" dataType="Reference" description="ME 4" row="6" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HiJ4O0OEeGWI9AsFWcjow" name="0002-001-13-C-1D" dataType="Reference" description="" row="1" column="13" referenceType="FgaMessageConst"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HjYAO0OEeGWI9AsFWcjow" name="0002-023-00-C-MW" dataType="Reference" description="" row="23" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HkmIO0OEeGWI9AsFWcjow" name="0002-043-00-C-AW" dataType="Reference" description="" row="43" column="0" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1Hl0QO0OEeGWI9AsFWcjow" name="0002-003-00-C-MW" dataType="Reference" description="ME 1" row="3" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HmbUO0OEeGWI9AsFWcjow" name="0002-002-13-C-1D" dataType="Reference" description="" row="2" column="13" referenceType="FgaMessageConst"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HnpcO0OEeGWI9AsFWcjow" name="0002-009-00-C-MW" dataType="Reference" description="ME 7" row="9" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HoQgO0OEeGWI9AsFWcjow" name="0002-002-01-C-1D" dataType="Reference" description="" row="2" column="1" referenceType="FgaMessageConst"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HpeoO0OEeGWI9AsFWcjow" name="0002-020-00-C-AW" dataType="Reference" description="AS 5" row="17" column="0" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HqFsO0OEeGWI9AsFWcjow" name="0002-022-00-C-MW" dataType="Reference" description="" row="22" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HqswO0OEeGWI9AsFWcjow" name="0002-033-00-C-MW" dataType="Reference" description="" row="30" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1Hr64O0OEeGWI9AsFWcjow" name="0002-038-00-C-AW" dataType="Reference" description="" row="38" column="0" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HtJAO0OEeGWI9AsFWcjow" name="0002-001-05-C-1D" dataType="Reference" description="" row="1" column="5" referenceType="FgaMessageConst"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HtwEO0OEeGWI9AsFWcjow" name="0002-000-12-C-BM" dataType="Reference" description="" column="12" referenceType="FgaMessageConst"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1Hu-MO0OEeGWI9AsFWcjow" name="0002-002-05-C-1D" dataType="Reference" description="" row="2" column="5" referenceType="FgaMessageConst"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HvlQO0OEeGWI9AsFWcjow" name="0002-016-00-C-AW" dataType="Reference" description="AS 1" row="13" column="0" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HwzYO0OEeGWI9AsFWcjow" name="0002-035-00-C-AW" dataType="Reference" description="" row="35" column="0" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HxacO0OEeGWI9AsFWcjow" name="0002-001-01-C-1D" dataType="Reference" description="" row="1" column="1" referenceType="FgaMessageConst"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HyokO0OEeGWI9AsFWcjow" name="0002-031-00-C-ZW" dataType="Reference" description="ZE 2" row="31" column="0"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1HzPoO0OEeGWI9AsFWcjow" name="0002-039-00-C-AW" dataType="Reference" description="" row="39" column="0" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1H0dwO0OEeGWI9AsFWcjow" name="0002-036-00-C-AW" dataType="Reference" description="" row="36" column="0" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1H1E0O0OEeGWI9AsFWcjow" name="0002-037-00-C-AW" dataType="Reference" description="" row="37" column="0" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1H2S8O0OEeGWI9AsFWcjow" name="0002-019-00-C-AW" dataType="Reference" description="AS 4" row="16" column="0" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1H26AO0OEeGWI9AsFWcjow" name="0002-041-00-C-AW" dataType="Reference" description="" row="41" column="0" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1H5WQO0OEeGWI9AsFWcjow" name="0002-042-00-C-AW" dataType="Reference" description="" row="42" column="0" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1H59UO0OEeGWI9AsFWcjow" name="0002-040-00-C-AW" dataType="Reference" description="" row="40" column="0" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1H7LcO0OEeGWI9AsFWcjow" name="0002-026-00-C-MW" dataType="Reference" description="" row="26" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1H7ygO0OEeGWI9AsFWcjow" name="0002-022-00-C-AW" dataType="Reference" description="AS 7" row="19" column="0" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1H9AoO0OEeGWI9AsFWcjow" name="0002-008-00-C-MW" dataType="Reference" description="ME 6" row="8" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1H-OwO0OEeGWI9AsFWcjow" name="0002-000-00-C-BM" dataType="Reference" description="" column="0" referenceType="FgaMessageConst"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1H_c4O0OEeGWI9AsFWcjow" name="0002-027-00-C-MW" dataType="Reference" description="" row="27" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1IArAO0OEeGWI9AsFWcjow" name="0002-000-13-C-1D" dataType="Reference" description="" column="13" referenceType="FgaMessageConst"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1IB5IO0OEeGWI9AsFWcjow" name="0002-023-00-C-AW" dataType="Reference" description="AS 8" row="20" column="0" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1IDHQO0OEeGWI9AsFWcjow" name="0002-017-00-C-AW" dataType="Reference" description="AS 2" row="14" column="0" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1IEVYO0OEeGWI9AsFWcjow" name="0002-012-00-C-MW" dataType="Reference" description="ME 10" row="12" column="0" referenceType="FgaMeasuredValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1IGKkO0OEeGWI9AsFWcjow" name="0002-000-04-C-BM" dataType="Reference" description="" column="4" referenceType="FgaMessageConst"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1IHYsO0OEeGWI9AsFWcjow" name="0002-018-00-C-AW" dataType="Reference" description="AS 3" row="15" column="0" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_1IIm0O0OEeGWI9AsFWcjow" name="0002-002-09-C-1D" dataType="Reference" description="" row="2" column="9" referenceType="FgaMessageConst"/>
    <attributes xsi:type="module:ConstantAttribute" xmi:id="_37sTkO0OEeGWI9AsFWcjow" name="enable" dataType="Word">
      <value xsi:type="module:WordValue" xmi:id="_37sTke0OEeGWI9AsFWcjow" value="1"/>
    </attributes>
    <attributes xsi:type="module:VariableAttribute" xmi:id="_BGsqkO0PEeGWI9AsFWcjow" name="$M0"/>
    <attributes xsi:type="module:ConstantAttribute" xmi:id="_aqQkYO0PEeGWI9AsFWcjow" name="tempGrenze">
      <value xsi:type="module:FloatValue" xmi:id="_aqQkYe0PEeGWI9AsFWcjow" value="25.0"/>
    </attributes>
    <attributes xsi:type="module:VariableAttribute" xmi:id="_ehq60O0PEeGWI9AsFWcjow" name="$M1" dataType="Word"/>
    <attributes xsi:type="module:VariableAttribute" xmi:id="_fagnUO0PEeGWI9AsFWcjow" name="$M2" dataType="Word"/>
    <attributes xsi:type="module:VariableAttribute" xmi:id="_A0GlEO0XEeG7krDSkOzqJg" name="$M3" dataType="Word"/>
    <attributes xsi:type="module:VariableAttribute" xmi:id="_BukCMO0XEeG7krDSkOzqJg" name="$M4" dataType="Word"/>
    <attributes xsi:type="module:VariableAttribute" xmi:id="_CiWPkO0XEeG7krDSkOzqJg" name="$M5" dataType="Word"/>
    <attributes xsi:type="module:VariableAttribute" xmi:id="_Jyh4oO0XEeG7krDSkOzqJg" name="$M6" dataType="Word"/>
    <tasks xmi:id="_os4nEO0OEeGWI9AsFWcjow" cycleTime="1000" index="1" name="Task_init"/>
    <tasks xmi:id="_pGy74O0OEeGWI9AsFWcjow" kind="CYCLIC" cycleTime="1000" index="2" name="Task_run_1">
      <pages xmi:id="_q4eU4O0OEeGWI9AsFWcjow" name="DemoDiagram">
        <fragmentElements xsi:type="dml:Block" xmi:id="_5g7MAO0OEeGWI9AsFWcjow" name="ANEIN">
          <inputs xsi:type="dml:BlockInput" xmi:id="_5g-2YO0OEeGWI9AsFWcjow">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_5g_dcO0OEeGWI9AsFWcjow"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/ANEIN.blocktype.dml#_j_On4IsyEd-AFYnRH2VIEQ"/>
          </inputs>
          <outputs xsi:type="dml:BlockOutput" xmi:id="_5hArkO0OEeGWI9AsFWcjow">
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_5hBSoO0OEeGWI9AsFWcjow">
              <signal xsi:type="module:AttributeSpecification" xmi:id="_BGsDgO0PEeGWI9AsFWcjow" attribute="_BGsqkO0PEeGWI9AsFWcjow"/>
            </ports>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/ANEIN.blocktype.dml#_wYaLEIsyEd-AFYnRH2VIEQ"/>
          </outputs>
          <outputs xsi:type="dml:BlockOutput" xmi:id="_5hCgwO0OEeGWI9AsFWcjow">
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_5hDH0O0OEeGWI9AsFWcjow"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/ANEIN.blocktype.dml#_qCsKcJCpEd-AgqF4Izs_FA"/>
          </outputs>
          <arguments xmi:id="_5g-PUO0OEeGWI9AsFWcjow">
            <value xsi:type="dml:ExpressionSpecification" xmi:id="_5hDu4O0OEeGWI9AsFWcjow" expression="1"/>
            <parameter xsi:type="dml:ExpressionParameter" href="http://www.wisag.de/automation/micas/library/1.0.0/Block.category.dml#_-McSwI2PEd-xLIzFfuJVQQ"/>
          </arguments>
          <type href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/ANEIN.blocktype.dml#_bO6BwIsyEd-AFYnRH2VIEQ"/>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Block" xmi:id="_8FfagO0OEeGWI9AsFWcjow" name="BEFAUS">
          <inputs xsi:type="dml:BlockInput" xmi:id="_8FgooO0OEeGWI9AsFWcjow">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_8Fh2wO0OEeGWI9AsFWcjow"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/BEFAUS.blocktype.dml#_j_On4IsyEd-AFYnRH2VIEQ"/>
          </inputs>
          <inputs xsi:type="dml:BlockInput" xmi:id="_8FjE4O0OEeGWI9AsFWcjow">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_8Fjr8O0OEeGWI9AsFWcjow"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/BEFAUS.blocktype.dml#_5RGwQJdKEd-YKM09ARBjYA"/>
          </inputs>
          <inputs xsi:type="dml:BlockInput" xmi:id="_8Fk6EO0OEeGWI9AsFWcjow">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_8FmIMO0OEeGWI9AsFWcjow"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/BEFAUS.blocktype.dml#_6S5kcJdKEd-YKM09ARBjYA"/>
          </inputs>
          <inputs xsi:type="dml:BlockInput" xmi:id="_8FnWUO0OEeGWI9AsFWcjow">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_8FokcO0OEeGWI9AsFWcjow"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/BEFAUS.blocktype.dml#_7mALEJdKEd-YKM09ARBjYA"/>
          </inputs>
          <inputs xsi:type="dml:BlockInput" xmi:id="_8FpykO0OEeGWI9AsFWcjow">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_8FqZoO0OEeGWI9AsFWcjow"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/BEFAUS.blocktype.dml#_FJlaIJdLEd-YKM09ARBjYA"/>
          </inputs>
          <outputs xsi:type="dml:BlockOutput" xmi:id="_8FrnwO0OEeGWI9AsFWcjow">
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_8Fs14O0OEeGWI9AsFWcjow"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/BEFAUS.blocktype.dml#_qCsKcJCpEd-AgqF4Izs_FA"/>
          </outputs>
          <arguments xmi:id="_8FgBkO0OEeGWI9AsFWcjow">
            <value xsi:type="dml:ExpressionSpecification" xmi:id="_8Ftc8O0OEeGWI9AsFWcjow" expression="2"/>
            <parameter xsi:type="dml:ExpressionParameter" href="http://www.wisag.de/automation/micas/library/1.0.0/Block.category.dml#_-McSwI2PEd-xLIzFfuJVQQ"/>
          </arguments>
          <type href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/BEFAUS.blocktype.dml#_bO6BwIsyEd-AFYnRH2VIEQ"/>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Block" xmi:id="_Pr1vAO0PEeGWI9AsFWcjow" name="VGLOH">
          <inputs xsi:type="dml:BlockInput" xmi:id="_Pr29IO0PEeGWI9AsFWcjow">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_Pr4LQO0PEeGWI9AsFWcjow"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/binaryanalog/VGLOH.blocktype.dml#_j_On4IsyEd-AFYnRH2VIEQ"/>
          </inputs>
          <inputs xsi:type="dml:BlockInput" xmi:id="_Pr5ZYO0PEeGWI9AsFWcjow">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_Pr6ngO0PEeGWI9AsFWcjow"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/binaryanalog/VGLOH.blocktype.dml#_sFqjgIsyEd-AFYnRH2VIEQ"/>
          </inputs>
          <outputs xsi:type="dml:BlockOutput" xmi:id="_Pr71oO0PEeGWI9AsFWcjow">
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_Pr8csO0PEeGWI9AsFWcjow">
              <signal xsi:type="module:AttributeSpecification" xmi:id="_fagAQO0PEeGWI9AsFWcjow" attribute="_fagnUO0PEeGWI9AsFWcjow"/>
            </ports>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/binaryanalog/VGLOH.blocktype.dml#_wYaLEIsyEd-AFYnRH2VIEQ"/>
          </outputs>
          <arguments xmi:id="_Pr2WEO0PEeGWI9AsFWcjow">
            <value xsi:type="dml:ExpressionSpecification" xmi:id="_Pr9q0O0PEeGWI9AsFWcjow" expression="3"/>
            <parameter xsi:type="dml:ExpressionParameter" href="http://www.wisag.de/automation/micas/library/1.0.0/Block.category.dml#_-McSwI2PEd-xLIzFfuJVQQ"/>
          </arguments>
          <type href="http://www.wisag.de/automation/micas/library/1.0.0/binaryanalog/VGLOH.blocktype.dml#_bO6BwIsyEd-AFYnRH2VIEQ"/>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_QXukoO0PEeGWI9AsFWcjow" source="_5hBSoO0OEeGWI9AsFWcjow" target="_Pr4LQO0PEeGWI9AsFWcjow" sourcePort="_5hBSoO0OEeGWI9AsFWcjow" targetPort="_Pr4LQO0PEeGWI9AsFWcjow"/>
        <fragmentElements xsi:type="module:Reference" xmi:id="_Rd0qAO0PEeGWI9AsFWcjow">
          <outputs xmi:id="_RehNkO0PEeGWI9AsFWcjow">
            <ports xmi:id="_RehNke0PEeGWI9AsFWcjow">
              <signal xsi:type="module:AttributeSpecification" xmi:id="_TBCJMO0PEeGWI9AsFWcjow" attribute="_1Hl0QO0OEeGWI9AsFWcjow"/>
            </ports>
          </outputs>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_UsqkkO0PEeGWI9AsFWcjow" source="_RehNke0PEeGWI9AsFWcjow" target="_5g_dcO0OEeGWI9AsFWcjow" sourcePort="_RehNke0PEeGWI9AsFWcjow" targetPort="_5g_dcO0OEeGWI9AsFWcjow"/>
        <fragmentElements xsi:type="module:Constant" xmi:id="_bky6AO0PEeGWI9AsFWcjow">
          <outputs xmi:id="_bk-gMO0PEeGWI9AsFWcjow">
            <ports xmi:id="_bk-gMe0PEeGWI9AsFWcjow">
              <signal xsi:type="module:AttributeSpecification" xmi:id="_b8m9EO0PEeGWI9AsFWcjow" attribute="_aqQkYO0PEeGWI9AsFWcjow"/>
            </ports>
          </outputs>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_cwU5AO0PEeGWI9AsFWcjow" source="_bk-gMe0PEeGWI9AsFWcjow" target="_Pr6ngO0PEeGWI9AsFWcjow" sourcePort="_bk-gMe0PEeGWI9AsFWcjow" targetPort="_Pr6ngO0PEeGWI9AsFWcjow"/>
        <fragmentElements xsi:type="dml:Block" xmi:id="_dvWGAO0PEeGWI9AsFWcjow" name="NICHT">
          <inputs xsi:type="dml:BlockInput" xmi:id="_dvX7MO0PEeGWI9AsFWcjow">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_dvZJUO0PEeGWI9AsFWcjow"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/binary/NICHT.blocktype.dml#_j_On4IsyEd-AFYnRH2VIEQ"/>
          </inputs>
          <outputs xsi:type="dml:BlockOutput" xmi:id="_dvaXcO0PEeGWI9AsFWcjow">
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_dvblkO0PEeGWI9AsFWcjow">
              <signal xsi:type="module:AttributeSpecification" xmi:id="_ehqTwO0PEeGWI9AsFWcjow" attribute="_ehq60O0PEeGWI9AsFWcjow"/>
            </ports>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/binary/NICHT.blocktype.dml#_wYaLEIsyEd-AFYnRH2VIEQ"/>
          </outputs>
          <arguments xmi:id="_dvXUIO0PEeGWI9AsFWcjow">
            <value xsi:type="dml:ExpressionSpecification" xmi:id="_dvczsO0PEeGWI9AsFWcjow" expression="4"/>
            <parameter xsi:type="dml:ExpressionParameter" href="http://www.wisag.de/automation/micas/library/1.0.0/Block.category.dml#_-McSwI2PEd-xLIzFfuJVQQ"/>
          </arguments>
          <type href="http://www.wisag.de/automation/micas/library/1.0.0/binary/NICHT.blocktype.dml#_bO6BwIsyEd-AFYnRH2VIEQ"/>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_ehoekO0PEeGWI9AsFWcjow" source="_dvblkO0PEeGWI9AsFWcjow" target="_8Fjr8O0OEeGWI9AsFWcjow" sourcePort="_dvblkO0PEeGWI9AsFWcjow" targetPort="_8Fjr8O0OEeGWI9AsFWcjow"/>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_faeyIO0PEeGWI9AsFWcjow" source="_Pr8csO0PEeGWI9AsFWcjow" target="_dvZJUO0PEeGWI9AsFWcjow" sourcePort="_Pr8csO0PEeGWI9AsFWcjow" targetPort="_dvZJUO0PEeGWI9AsFWcjow"/>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_f4xQoO0PEeGWI9AsFWcjow" source="_Pr8csO0PEeGWI9AsFWcjow" target="_8Fh2wO0OEeGWI9AsFWcjow" sourcePort="_Pr8csO0PEeGWI9AsFWcjow" targetPort="_8Fh2wO0OEeGWI9AsFWcjow"/>
        <fragmentElements xsi:type="module:Reference" xmi:id="_hbeZgO0PEeGWI9AsFWcjow">
          <outputs xmi:id="_hbfAkO0PEeGWI9AsFWcjow">
            <ports xmi:id="_hbfAke0PEeGWI9AsFWcjow">
              <signal xsi:type="module:AttributeSpecification" xmi:id="_N8_VoO0REeGWI9AsFWcjow" attribute="_1HxacO0OEeGWI9AsFWcjow"/>
            </ports>
          </outputs>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_i9JAkO0PEeGWI9AsFWcjow" source="_hbfAke0PEeGWI9AsFWcjow" target="_8FqZoO0OEeGWI9AsFWcjow" sourcePort="_hbfAke0PEeGWI9AsFWcjow" targetPort="_8FqZoO0OEeGWI9AsFWcjow"/>
        <fragmentElements xsi:type="dml:Block" xmi:id="_8qpcYO0WEeG7krDSkOzqJg" name="MELEIN">
          <inputs xsi:type="dml:BlockInput" xmi:id="_8q1poO0WEeG7krDSkOzqJg">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_8q4s8O0WEeG7krDSkOzqJg"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/MELEIN.blocktype.dml#_j_On4IsyEd-AFYnRH2VIEQ"/>
          </inputs>
          <outputs xsi:type="dml:BlockOutput" xmi:id="_8q57EO0WEeG7krDSkOzqJg">
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_8q7wQO0WEeG7krDSkOzqJg">
              <signal xsi:type="module:AttributeSpecification" xmi:id="_A0FW8O0XEeG7krDSkOzqJg" attribute="_A0GlEO0XEeG7krDSkOzqJg"/>
            </ports>
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_9NRBQO0WEeG7krDSkOzqJg">
              <signal xsi:type="module:AttributeSpecification" xmi:id="_BujbIO0XEeG7krDSkOzqJg" attribute="_BukCMO0XEeG7krDSkOzqJg"/>
            </ports>
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_9jlPgO0WEeG7krDSkOzqJg">
              <signal xsi:type="module:AttributeSpecification" xmi:id="_CiVBcO0XEeG7krDSkOzqJg" attribute="_CiWPkO0XEeG7krDSkOzqJg"/>
            </ports>
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_92lEAO0WEeG7krDSkOzqJg">
              <signal xsi:type="module:AttributeSpecification" xmi:id="_JyhRkO0XEeG7krDSkOzqJg" attribute="_Jyh4oO0XEeG7krDSkOzqJg"/>
            </ports>
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_-GJKAO0WEeG7krDSkOzqJg"/>
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_-Vo-kO0WEeG7krDSkOzqJg"/>
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_-mpPAO0WEeG7krDSkOzqJg"/>
            <ports xsi:type="dml:BlockOutputPort" xmi:id="__BNEEO0WEeG7krDSkOzqJg"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/MELEIN.blocktype.dml#_1eRDga-CEd-BLuEWVmQTyw"/>
          </outputs>
          <outputs xsi:type="dml:BlockOutput" xmi:id="_8q8XUO0WEeG7krDSkOzqJg">
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_8q9lcO0WEeG7krDSkOzqJg"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/MELEIN.blocktype.dml#_qCsKcJCpEd-AgqF4Izs_FA"/>
          </outputs>
          <arguments xmi:id="_8qz0cO0WEeG7krDSkOzqJg">
            <value xsi:type="dml:ExpressionSpecification" xmi:id="_8rrXIO0WEeG7krDSkOzqJg" expression="5"/>
            <parameter xsi:type="dml:ExpressionParameter" href="http://www.wisag.de/automation/micas/library/1.0.0/Block.category.dml#_-McSwI2PEd-xLIzFfuJVQQ"/>
          </arguments>
          <type href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/MELEIN.blocktype.dml#_bO6BwIsyEd-AFYnRH2VIEQ"/>
        </fragmentElements>
        <fragmentElements xsi:type="module:OutgoingOffpageConnector" xmi:id="_AR2zoO0XEeG7krDSkOzqJg">
          <inputs xmi:id="_ASj-QO0XEeG7krDSkOzqJg">
            <ports xmi:id="_ASj-Qe0XEeG7krDSkOzqJg"/>
          </inputs>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_Az-pQO0XEeG7krDSkOzqJg" source="_8q7wQO0WEeG7krDSkOzqJg" target="_ASj-Qe0XEeG7krDSkOzqJg" sourcePort="_8q7wQO0WEeG7krDSkOzqJg" targetPort="_ASj-Qe0XEeG7krDSkOzqJg"/>
        <fragmentElements xsi:type="module:OutgoingOffpageConnector" xmi:id="_BP4iIO0XEeG7krDSkOzqJg">
          <inputs xmi:id="_BP6XUO0XEeG7krDSkOzqJg">
            <ports xmi:id="_BP6XUe0XEeG7krDSkOzqJg"/>
          </inputs>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_BufwwO0XEeG7krDSkOzqJg" source="_9NRBQO0WEeG7krDSkOzqJg" target="_BP6XUe0XEeG7krDSkOzqJg" sourcePort="_9NRBQO0WEeG7krDSkOzqJg" targetPort="_BP6XUe0XEeG7krDSkOzqJg"/>
        <fragmentElements xsi:type="module:OutgoingOffpageConnector" xmi:id="_CDw2IO0XEeG7krDSkOzqJg">
          <inputs xmi:id="_CDyrUO0XEeG7krDSkOzqJg">
            <ports xmi:id="_CDyrUe0XEeG7krDSkOzqJg"/>
          </inputs>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_CiOTwO0XEeG7krDSkOzqJg" source="_9jlPgO0WEeG7krDSkOzqJg" target="_CDyrUe0XEeG7krDSkOzqJg" sourcePort="_9jlPgO0WEeG7krDSkOzqJg" targetPort="_CDyrUe0XEeG7krDSkOzqJg"/>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_D0S_oO0XEeG7krDSkOzqJg" source="_hbfAke0PEeGWI9AsFWcjow" target="_8q4s8O0WEeG7krDSkOzqJg" sourcePort="_hbfAke0PEeGWI9AsFWcjow" targetPort="_8q4s8O0WEeG7krDSkOzqJg"/>
        <fragmentElements xsi:type="module:OutgoingOffpageConnector" xmi:id="_JRpZIO0XEeG7krDSkOzqJg">
          <inputs xmi:id="_JRrOUO0XEeG7krDSkOzqJg">
            <ports xmi:id="_JRrOUe0XEeG7krDSkOzqJg"/>
          </inputs>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_JyeOQO0XEeG7krDSkOzqJg" source="_92lEAO0WEeG7krDSkOzqJg" target="_JRrOUe0XEeG7krDSkOzqJg" sourcePort="_92lEAO0WEeG7krDSkOzqJg" targetPort="_JRrOUe0XEeG7krDSkOzqJg"/>
      </pages>
    </tasks>
  </module:Module>
  <notation:Diagram xmi:id="_q4h_QO0OEeGWI9AsFWcjow" element="_q4eU4O0OEeGWI9AsFWcjow" name="wes net" measurementUnit="Himetric">
    <children xmi:id="_5hGyMO0OEeGWI9AsFWcjow" element="_5g7MAO0OEeGWI9AsFWcjow">
      <children xmi:id="_5hHZQO0OEeGWI9AsFWcjow" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_5hHZQe0OEeGWI9AsFWcjow" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_5hHZQu0OEeGWI9AsFWcjow"/>
      </children>
      <children xmi:id="_5hKckO0OEeGWI9AsFWcjow" element="_5g_dcO0OEeGWI9AsFWcjow">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_5hKcke0OEeGWI9AsFWcjow" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_5hLDoO0OEeGWI9AsFWcjow"/>
      </children>
      <children xmi:id="_5hLqsO0OEeGWI9AsFWcjow" element="_5hBSoO0OEeGWI9AsFWcjow">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_5hLqse0OEeGWI9AsFWcjow" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_5hLqsu0OEeGWI9AsFWcjow"/>
      </children>
      <children xmi:id="_5hM40O0OEeGWI9AsFWcjow" element="_5hDH0O0OEeGWI9AsFWcjow">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_5hM40e0OEeGWI9AsFWcjow" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_5hM40u0OEeGWI9AsFWcjow"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_5hGyMe0OEeGWI9AsFWcjow" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_5hGyMu0OEeGWI9AsFWcjow" x="6393" y="3420"/>
    </children>
    <children xmi:id="_8FxHUO0OEeGWI9AsFWcjow" element="_8FfagO0OEeGWI9AsFWcjow">
      <children xmi:id="_8FyVcO0OEeGWI9AsFWcjow" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_8FyVce0OEeGWI9AsFWcjow" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_8FyVcu0OEeGWI9AsFWcjow"/>
      </children>
      <children xmi:id="_8F2m4O0OEeGWI9AsFWcjow" element="_8Fh2wO0OEeGWI9AsFWcjow">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_8F2m4e0OEeGWI9AsFWcjow" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_8F2m4u0OEeGWI9AsFWcjow"/>
      </children>
      <children xmi:id="_8F31AO0OEeGWI9AsFWcjow" element="_8Fjr8O0OEeGWI9AsFWcjow">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_8F31Ae0OEeGWI9AsFWcjow" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_8F31Au0OEeGWI9AsFWcjow"/>
      </children>
      <children xmi:id="_8F5DIO0OEeGWI9AsFWcjow" element="_8FmIMO0OEeGWI9AsFWcjow">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_8F5DIe0OEeGWI9AsFWcjow" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_8F5DIu0OEeGWI9AsFWcjow"/>
      </children>
      <children xmi:id="_8F6RQO0OEeGWI9AsFWcjow" element="_8FokcO0OEeGWI9AsFWcjow">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_8F6RQe0OEeGWI9AsFWcjow" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_8F6RQu0OEeGWI9AsFWcjow"/>
      </children>
      <children xmi:id="_8F64UO0OEeGWI9AsFWcjow" element="_8FqZoO0OEeGWI9AsFWcjow">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_8F64Ue0OEeGWI9AsFWcjow" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_8F64Uu0OEeGWI9AsFWcjow"/>
      </children>
      <children xmi:id="_8F8GcO0OEeGWI9AsFWcjow" element="_8Fs14O0OEeGWI9AsFWcjow">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_8F8Gce0OEeGWI9AsFWcjow" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_8F8Gcu0OEeGWI9AsFWcjow"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_8FxHUe0OEeGWI9AsFWcjow" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_8FxHUu0OEeGWI9AsFWcjow" x="18430" y="3420"/>
    </children>
    <children xmi:id="_PsAuIO0PEeGWI9AsFWcjow" element="_Pr1vAO0PEeGWI9AsFWcjow">
      <children xmi:id="_PsB8QO0PEeGWI9AsFWcjow" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_PsB8Qe0PEeGWI9AsFWcjow" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_PsB8Qu0PEeGWI9AsFWcjow"/>
      </children>
      <children xmi:id="_PsGNsO0PEeGWI9AsFWcjow" element="_Pr4LQO0PEeGWI9AsFWcjow">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_PsGNse0PEeGWI9AsFWcjow" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_PsGNsu0PEeGWI9AsFWcjow"/>
      </children>
      <children xmi:id="_PsG0wO0PEeGWI9AsFWcjow" element="_Pr6ngO0PEeGWI9AsFWcjow">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_PsG0we0PEeGWI9AsFWcjow" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_PsG0wu0PEeGWI9AsFWcjow"/>
      </children>
      <children xmi:id="_PsHb0O0PEeGWI9AsFWcjow" element="_Pr8csO0PEeGWI9AsFWcjow">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_PsIC4O0PEeGWI9AsFWcjow" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_PsIC4e0PEeGWI9AsFWcjow"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_PsAuIe0PEeGWI9AsFWcjow" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_PsAuIu0PEeGWI9AsFWcjow" x="11400" y="3420"/>
    </children>
    <children xmi:id="_Rejp0O0PEeGWI9AsFWcjow" element="_Rd0qAO0PEeGWI9AsFWcjow">
      <children xmi:id="_Rek38O0PEeGWI9AsFWcjow" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_Rek38e0PEeGWI9AsFWcjow" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_Rek38u0PEeGWI9AsFWcjow"/>
      </children>
      <children xmi:id="_RepwcO0PEeGWI9AsFWcjow" element="_RehNke0PEeGWI9AsFWcjow">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_Repwce0PEeGWI9AsFWcjow" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_Repwcu0PEeGWI9AsFWcjow"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_Rejp0e0PEeGWI9AsFWcjow" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_Rejp0u0PEeGWI9AsFWcjow" x="760" y="3875"/>
    </children>
    <children xmi:id="_blAVYO0PEeGWI9AsFWcjow" element="_bky6AO0PEeGWI9AsFWcjow">
      <children xmi:id="_blCKkO0PEeGWI9AsFWcjow" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_blCKke0PEeGWI9AsFWcjow" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_blCKku0PEeGWI9AsFWcjow"/>
      </children>
      <children xmi:id="_blGcAO0PEeGWI9AsFWcjow" element="_bk-gMe0PEeGWI9AsFWcjow">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_blGcAe0PEeGWI9AsFWcjow" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_blGcAu0PEeGWI9AsFWcjow"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_blAVYe0PEeGWI9AsFWcjow" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_blAVYu0PEeGWI9AsFWcjow" x="7133" y="6519"/>
    </children>
    <children xmi:id="_dvfP8O0PEeGWI9AsFWcjow" element="_dvWGAO0PEeGWI9AsFWcjow">
      <children xmi:id="_dvhFIO0PEeGWI9AsFWcjow" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_dvhFIe0PEeGWI9AsFWcjow" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_dvhFIu0PEeGWI9AsFWcjow"/>
      </children>
      <children xmi:id="_dvl9oO0PEeGWI9AsFWcjow" element="_dvZJUO0PEeGWI9AsFWcjow">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_dvl9oe0PEeGWI9AsFWcjow" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_dvl9ou0PEeGWI9AsFWcjow"/>
      </children>
      <children xmi:id="_dvny0O0PEeGWI9AsFWcjow" element="_dvblkO0PEeGWI9AsFWcjow">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_dvny0e0PEeGWI9AsFWcjow" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_dvny0u0PEeGWI9AsFWcjow"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_dvfP8e0PEeGWI9AsFWcjow" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_dvfP8u0PEeGWI9AsFWcjow" x="15390" y="4629"/>
    </children>
    <children xmi:id="_hbg1wO0PEeGWI9AsFWcjow" element="_hbeZgO0PEeGWI9AsFWcjow">
      <children xmi:id="_hbiq8O0PEeGWI9AsFWcjow" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_hbiq8e0PEeGWI9AsFWcjow" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_hbiq8u0PEeGWI9AsFWcjow"/>
      </children>
      <children xmi:id="_hbmVUO0PEeGWI9AsFWcjow" element="_hbfAke0PEeGWI9AsFWcjow">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_hbm8YO0PEeGWI9AsFWcjow" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_hbm8Ye0PEeGWI9AsFWcjow"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_hbg1we0PEeGWI9AsFWcjow" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_hbg1wu0PEeGWI9AsFWcjow" x="12350" y="8170"/>
    </children>
    <children xmi:id="_8sX6sO0WEeG7krDSkOzqJg" element="_8qpcYO0WEeG7krDSkOzqJg">
      <children xmi:id="_8saW8O0WEeG7krDSkOzqJg" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_8saW8e0WEeG7krDSkOzqJg" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_8saW8u0WEeG7krDSkOzqJg"/>
      </children>
      <children xmi:id="_8seoYO0WEeG7krDSkOzqJg" element="_8q4s8O0WEeG7krDSkOzqJg">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_8seoYe0WEeG7krDSkOzqJg" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_8seoYu0WEeG7krDSkOzqJg"/>
      </children>
      <children xmi:id="_8shEoO0WEeG7krDSkOzqJg" element="_8q7wQO0WEeG7krDSkOzqJg">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_8shEoe0WEeG7krDSkOzqJg" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_8shEou0WEeG7krDSkOzqJg"/>
      </children>
      <children xmi:id="_8sjg4O0WEeG7krDSkOzqJg" element="_8q9lcO0WEeG7krDSkOzqJg">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_8sjg4e0WEeG7krDSkOzqJg" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_8sjg4u0WEeG7krDSkOzqJg"/>
      </children>
      <children xmi:id="_9NVSsO0WEeG7krDSkOzqJg" element="_9NRBQO0WEeG7krDSkOzqJg">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_9NVSse0WEeG7krDSkOzqJg" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_9NVSsu0WEeG7krDSkOzqJg"/>
      </children>
      <children xmi:id="_9jpg8O0WEeG7krDSkOzqJg" element="_9jlPgO0WEeG7krDSkOzqJg">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_9jpg8e0WEeG7krDSkOzqJg" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_9jpg8u0WEeG7krDSkOzqJg"/>
      </children>
      <children xmi:id="_92p8gO0WEeG7krDSkOzqJg" element="_92lEAO0WEeG7krDSkOzqJg">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_92p8ge0WEeG7krDSkOzqJg" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_92p8gu0WEeG7krDSkOzqJg"/>
      </children>
      <children xmi:id="_-GNbcO0WEeG7krDSkOzqJg" element="_-GJKAO0WEeG7krDSkOzqJg">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_-GNbce0WEeG7krDSkOzqJg" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_-GNbcu0WEeG7krDSkOzqJg"/>
      </children>
      <children xmi:id="_-VtQAO0WEeG7krDSkOzqJg" element="_-Vo-kO0WEeG7krDSkOzqJg">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_-VtQAe0WEeG7krDSkOzqJg" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_-VtQAu0WEeG7krDSkOzqJg"/>
      </children>
      <children xmi:id="_-muHgO0WEeG7krDSkOzqJg" element="_-mpPAO0WEeG7krDSkOzqJg">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_-muHge0WEeG7krDSkOzqJg" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_-muHgu0WEeG7krDSkOzqJg"/>
      </children>
      <children xmi:id="__BRVgO0WEeG7krDSkOzqJg" element="__BNEEO0WEeG7krDSkOzqJg">
        <styles xsi:type="notation:ShapeStyle" xmi:id="__BRVge0WEeG7krDSkOzqJg" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="__BRVgu0WEeG7krDSkOzqJg"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_8sX6se0WEeG7krDSkOzqJg" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_8sX6su0WEeG7krDSkOzqJg" x="3420" y="7410"/>
    </children>
    <children xmi:id="_ASnBkO0XEeG7krDSkOzqJg" element="_AR2zoO0XEeG7krDSkOzqJg">
      <children xmi:id="_ASr6EO0XEeG7krDSkOzqJg" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_ASr6Ee0XEeG7krDSkOzqJg" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_ASr6Eu0XEeG7krDSkOzqJg"/>
      </children>
      <children xmi:id="_AS2SIO0XEeG7krDSkOzqJg" element="_ASj-Qe0XEeG7krDSkOzqJg">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_AS2SIe0XEeG7krDSkOzqJg" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_AS2SIu0XEeG7krDSkOzqJg"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_ASnooO0XEeG7krDSkOzqJg" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_ASnooe0XEeG7krDSkOzqJg" x="9120" y="7862"/>
    </children>
    <children xmi:id="_BP-BsO0XEeG7krDSkOzqJg" element="_BP4iIO0XEeG7krDSkOzqJg">
      <children xmi:id="_BQBsEO0XEeG7krDSkOzqJg" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_BQCTIO0XEeG7krDSkOzqJg" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_BQCTIe0XEeG7krDSkOzqJg"/>
      </children>
      <children xmi:id="_BQNSQO0XEeG7krDSkOzqJg" element="_BP6XUe0XEeG7krDSkOzqJg">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_BQNSQe0XEeG7krDSkOzqJg" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_BQNSQu0XEeG7krDSkOzqJg"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_BP-Bse0XEeG7krDSkOzqJg" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_BP-Bsu0XEeG7krDSkOzqJg" x="10356" y="8343"/>
    </children>
    <children xmi:id="_CD1uoO0XEeG7krDSkOzqJg" element="_CDw2IO0XEeG7krDSkOzqJg">
      <children xmi:id="_CD5ZAO0XEeG7krDSkOzqJg" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_CD5ZAe0XEeG7krDSkOzqJg" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_CD5ZAu0XEeG7krDSkOzqJg"/>
      </children>
      <children xmi:id="_CEAGsO0XEeG7krDSkOzqJg" element="_CDyrUe0XEeG7krDSkOzqJg">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_CEAGse0XEeG7krDSkOzqJg" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_CEAGsu0XEeG7krDSkOzqJg"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_CD1uoe0XEeG7krDSkOzqJg" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_CD1uou0XEeG7krDSkOzqJg" x="9120" y="8824"/>
    </children>
    <children xmi:id="_JRtqkO0XEeG7krDSkOzqJg" element="_JRpZIO0XEeG7krDSkOzqJg">
      <children xmi:id="_JRwG0O0XEeG7krDSkOzqJg" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_JRwG0e0XEeG7krDSkOzqJg" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_JRwG0u0XEeG7krDSkOzqJg"/>
      </children>
      <children xmi:id="_JR1mYO0XEeG7krDSkOzqJg" element="_JRrOUe0XEeG7krDSkOzqJg">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_JR2NcO0XEeG7krDSkOzqJg" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_JR2Nce0XEeG7krDSkOzqJg"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_JRtqke0XEeG7krDSkOzqJg" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_JRtqku0XEeG7krDSkOzqJg" x="10356" y="9305"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_p3XbMO0kEeGiY6CEy711vg" type="Note" fontName="Segoe UI" description="Liest Temp von PT1000" fillColor="13369343" transparency="0" lineColor="6737151" lineWidth="1">
      <children xsi:type="notation:BasicDecorationNode" xmi:id="_p3kPgO0kEeGiY6CEy711vg" type="DiagramName">
        <element xsi:nil="true"/>
      </children>
      <children xsi:type="notation:BasicDecorationNode" xmi:id="_p3ldoO0kEeGiY6CEy711vg" type="Description">
        <element xsi:nil="true"/>
      </children>
      <styles xsi:type="notation:TextStyle" xmi:id="_p3XbMe0kEeGiY6CEy711vg"/>
      <styles xsi:type="notation:LineTypeStyle" xmi:id="_p3XbMu0kEeGiY6CEy711vg"/>
      <element xsi:nil="true"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_p3XbM-0kEeGiY6CEy711vg" x="582" y="1940"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_u3rTYO0kEeGiY6CEy711vg" type="Note" fontName="Segoe UI" description="VGLOH sendet 1 bei x> Grenze" fillColor="13369343" transparency="0" lineColor="6737151" lineWidth="1">
      <children xsi:type="notation:BasicDecorationNode" xmi:id="_u36j8O0kEeGiY6CEy711vg" type="DiagramName">
        <element xsi:nil="true"/>
      </children>
      <children xsi:type="notation:BasicDecorationNode" xmi:id="_u37yEO0kEeGiY6CEy711vg" type="Description">
        <element xsi:nil="true"/>
      </children>
      <styles xsi:type="notation:TextStyle" xmi:id="_u3rTYe0kEeGiY6CEy711vg"/>
      <styles xsi:type="notation:LineTypeStyle" xmi:id="_u3rTYu0kEeGiY6CEy711vg"/>
      <element xsi:nil="true"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_u3rTY-0kEeGiY6CEy711vg" x="10123" y="844"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_2-jT4O0kEeGiY6CEy711vg" type="Note" fontName="Segoe UI" description="Befehl 9" fillColor="13369343" transparency="0" lineColor="6737151" lineWidth="1">
      <children xsi:type="notation:BasicDecorationNode" xmi:id="_2-zykO0kEeGiY6CEy711vg" type="DiagramName">
        <element xsi:nil="true"/>
      </children>
      <children xsi:type="notation:BasicDecorationNode" xmi:id="_2-4rEO0kEeGiY6CEy711vg" type="Description">
        <element xsi:nil="true"/>
      </children>
      <styles xsi:type="notation:TextStyle" xmi:id="_2-jT4e0kEeGiY6CEy711vg"/>
      <styles xsi:type="notation:LineTypeStyle" xmi:id="_2-jT4u0kEeGiY6CEy711vg"/>
      <element xsi:nil="true"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_2-jT4-0kEeGiY6CEy711vg" x="16880" y="8876"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_A3GGUO0lEeGiY6CEy711vg" type="Note" fontName="Segoe UI" description="Wenn temparatur über grenze geht, klackert das Relais" fillColor="13369343" transparency="0" lineColor="6737151" lineWidth="1">
      <children xsi:type="notation:BasicDecorationNode" xmi:id="_A3Uv0O0lEeGiY6CEy711vg" type="DiagramName">
        <element xsi:nil="true"/>
      </children>
      <children xsi:type="notation:BasicDecorationNode" xmi:id="_A3ZoUO0lEeGiY6CEy711vg" type="Description">
        <element xsi:nil="true"/>
      </children>
      <styles xsi:type="notation:TextStyle" xmi:id="_A3GtYO0lEeGiY6CEy711vg"/>
      <styles xsi:type="notation:LineTypeStyle" xmi:id="_A3GtYe0lEeGiY6CEy711vg"/>
      <element xsi:nil="true"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_A3GtYu0lEeGiY6CEy711vg" x="18018" y="661"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_Ksh6YO0lEeGiY6CEy711vg" type="Note" fontName="Segoe UI" description="$M3 $M5 stellen Relais dar" fillColor="13369343" transparency="0" lineColor="6737151" lineWidth="1">
      <children xsi:type="notation:BasicDecorationNode" xmi:id="_Ksv80O0lEeGiY6CEy711vg" type="DiagramName">
        <element xsi:nil="true"/>
      </children>
      <children xsi:type="notation:BasicDecorationNode" xmi:id="_KsznMO0lEeGiY6CEy711vg" type="Description">
        <element xsi:nil="true"/>
      </children>
      <styles xsi:type="notation:TextStyle" xmi:id="_Ksh6Ye0lEeGiY6CEy711vg"/>
      <styles xsi:type="notation:LineTypeStyle" xmi:id="_Ksh6Yu0lEeGiY6CEy711vg"/>
      <element xsi:nil="true"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_Ksh6Y-0lEeGiY6CEy711vg" x="8093" y="10128"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_VvOy0O0lEeGiY6CEy711vg" type="Note" fontName="Segoe UI" description="Handkarte ohne Potis: Oberster Schalter : A=Automatik, MICAS hat Kontrolle. 0=Aus, 1= DAUER-EIN " fillColor="13369343" transparency="0" lineColor="6737151" lineWidth="1">
      <children xsi:type="notation:BasicDecorationNode" xmi:id="_VvdcUO0lEeGiY6CEy711vg" type="DiagramName">
        <element xsi:nil="true"/>
      </children>
      <children xsi:type="notation:BasicDecorationNode" xmi:id="_VvhtwO0lEeGiY6CEy711vg" type="Description">
        <element xsi:nil="true"/>
      </children>
      <styles xsi:type="notation:TextStyle" xmi:id="_VvOy0e0lEeGiY6CEy711vg"/>
      <styles xsi:type="notation:LineTypeStyle" xmi:id="_VvOy0u0lEeGiY6CEy711vg"/>
      <element xsi:nil="true"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_VvOy0-0lEeGiY6CEy711vg" x="23045" y="3439" width="3967" height="2486"/>
    </children>
    <children xsi:type="notation:Shape" xmi:id="_C18jMO0mEeGiY6CEy711vg" type="Note" fontName="Segoe UI" fontHeight="16" description="Zum Testen tempGrenze verschieben" fillColor="13369343" transparency="0" lineColor="6737151" lineWidth="1">
      <children xsi:type="notation:BasicDecorationNode" xmi:id="_C2G7QO0mEeGiY6CEy711vg" type="DiagramName">
        <element xsi:nil="true"/>
      </children>
      <children xsi:type="notation:BasicDecorationNode" xmi:id="_C2IJYO0mEeGiY6CEy711vg" type="Description">
        <element xsi:nil="true"/>
      </children>
      <styles xsi:type="notation:TextStyle" xmi:id="_C18jMe0mEeGiY6CEy711vg"/>
      <styles xsi:type="notation:LineTypeStyle" xmi:id="_C18jMu0mEeGiY6CEy711vg"/>
      <element xsi:nil="true"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_C18jM-0mEeGiY6CEy711vg" x="436" y="211"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_q4h_Qe0OEeGWI9AsFWcjow"/>
    <edges xmi:id="_QXwZ0O0PEeGWI9AsFWcjow" element="_QXukoO0PEeGWI9AsFWcjow" source="_5hLqsO0OEeGWI9AsFWcjow" target="_PsGNsO0PEeGWI9AsFWcjow">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_QXxA4O0PEeGWI9AsFWcjow" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_QXxA4e0PEeGWI9AsFWcjow" points="[0, 0, -125, -21]$[125, 21, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_QX2gcO0PEeGWI9AsFWcjow" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_QX3HgO0PEeGWI9AsFWcjow" id="port"/>
    </edges>
    <edges xmi:id="_UstA0O0PEeGWI9AsFWcjow" element="_UsqkkO0PEeGWI9AsFWcjow" source="_RepwcO0PEeGWI9AsFWcjow" target="_5hKckO0OEeGWI9AsFWcjow">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_UstA0e0PEeGWI9AsFWcjow" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_UstA0u0PEeGWI9AsFWcjow" points="[0, 0, -102, -3]$[102, 3, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_UsygYO0PEeGWI9AsFWcjow" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_UsygYe0PEeGWI9AsFWcjow" id="port"/>
    </edges>
    <edges xmi:id="_cwWHIO0PEeGWI9AsFWcjow" element="_cwU5AO0PEeGWI9AsFWcjow" source="_blGcAO0PEeGWI9AsFWcjow" target="_PsG0wO0PEeGWI9AsFWcjow">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_cwWHIe0PEeGWI9AsFWcjow" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_cwWHIu0PEeGWI9AsFWcjow" points="[0, 0, -80, 102]$[80, -102, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_cwYjYO0PEeGWI9AsFWcjow" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_cwYjYe0PEeGWI9AsFWcjow" id="port"/>
    </edges>
    <edges xmi:id="_ehtXEO0PEeGWI9AsFWcjow" element="_ehoekO0PEeGWI9AsFWcjow" source="_dvny0O0PEeGWI9AsFWcjow" target="_8F31AO0OEeGWI9AsFWcjow">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_ehtXEe0PEeGWI9AsFWcjow" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_eht-IO0PEeGWI9AsFWcjow" points="[0, 0, -91, 11]$[91, -11, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_eh0r0O0PEeGWI9AsFWcjow" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_eh1S4O0PEeGWI9AsFWcjow" id="port"/>
    </edges>
    <edges xmi:id="_fajDkO0PEeGWI9AsFWcjow" element="_faeyIO0PEeGWI9AsFWcjow" source="_PsHb0O0PEeGWI9AsFWcjow" target="_dvl9oO0PEeGWI9AsFWcjow">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_fajDke0PEeGWI9AsFWcjow" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_fajDku0PEeGWI9AsFWcjow" points="[0, 0, -81, -23]$[81, 23, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_fanVAO0PEeGWI9AsFWcjow" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_fan8EO0PEeGWI9AsFWcjow" id="port"/>
    </edges>
    <edges xmi:id="_f4zs4O0PEeGWI9AsFWcjow" element="_f4xQoO0PEeGWI9AsFWcjow" source="_PsHb0O0PEeGWI9AsFWcjow" target="_8F2m4O0OEeGWI9AsFWcjow">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_f4zs4e0PEeGWI9AsFWcjow" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_f4zs4u0PEeGWI9AsFWcjow" points="[0, 0, -224, 11]$[224, -11, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_f44lYO0PEeGWI9AsFWcjow" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_f44lYe0PEeGWI9AsFWcjow" id="port"/>
    </edges>
    <edges xmi:id="_i9MD4O0PEeGWI9AsFWcjow" element="_i9JAkO0PEeGWI9AsFWcjow" source="_hbmVUO0PEeGWI9AsFWcjow" target="_8F64UO0OEeGWI9AsFWcjow">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_i9MD4e0PEeGWI9AsFWcjow" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_i9MD4u0PEeGWI9AsFWcjow" points="[0, 0, -122, 123]$[122, -123, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_i9Q8YO0PEeGWI9AsFWcjow" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_i9RjcO0PEeGWI9AsFWcjow" id="port"/>
    </edges>
    <edges xmi:id="_A0KPcO0XEeG7krDSkOzqJg" element="_Az-pQO0XEeG7krDSkOzqJg" source="_8shEoO0WEeG7krDSkOzqJg" target="_AS2SIO0XEeG7krDSkOzqJg">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_A0KPce0XEeG7krDSkOzqJg" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_A0KPcu0XEeG7krDSkOzqJg" points="[0, 0, -94, 11]$[94, -11, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_A0auIO0XEeG7krDSkOzqJg" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_A0bVMO0XEeG7krDSkOzqJg" id="port"/>
    </edges>
    <edges xmi:id="_BumecO0XEeG7krDSkOzqJg" element="_BufwwO0XEeG7krDSkOzqJg" source="_9NVSsO0WEeG7krDSkOzqJg" target="_BQNSQO0XEeG7krDSkOzqJg">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_Bumece0XEeG7krDSkOzqJg" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_Bumecu0XEeG7krDSkOzqJg" points="[0, 0, -90, -20]$[90, 20, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BuyEoO0XEeG7krDSkOzqJg" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_BuyEoe0XEeG7krDSkOzqJg" id="port"/>
    </edges>
    <edges xmi:id="_CiYEwO0XEeG7krDSkOzqJg" element="_CiOTwO0XEeG7krDSkOzqJg" source="_9jpg8O0WEeG7krDSkOzqJg" target="_CEAGsO0XEeG7krDSkOzqJg">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_CiYEwe0XEeG7krDSkOzqJg" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_CiYEwu0XEeG7krDSkOzqJg" points="[0, 0, -110, -38]$[110, 38, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_CimHMO0XEeG7krDSkOzqJg" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_CinVUO0XEeG7krDSkOzqJg" id="port"/>
    </edges>
    <edges xmi:id="_D0XREO0XEeG7krDSkOzqJg" element="_D0S_oO0XEeG7krDSkOzqJg" source="_hbmVUO0PEeGWI9AsFWcjow" target="_8seoYO0WEeG7krDSkOzqJg">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_D0XREe0XEeG7krDSkOzqJg" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_D0XREu0XEeG7krDSkOzqJg" points="[0, 0, 12241, 308]$[658, 0, 12899, 308]$[658, 5383, 12899, 5691]$[-13778, 5383, -1537, 5691]$[-13778, -308, -1537, 0]$[-12241, -308, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_D0el0O0XEeG7krDSkOzqJg" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_D0fM4O0XEeG7krDSkOzqJg" id="port"/>
    </edges>
    <edges xmi:id="_JykU4O0XEeG7krDSkOzqJg" element="_JyeOQO0XEeG7krDSkOzqJg" source="_92p8gO0WEeG7krDSkOzqJg" target="_JR1mYO0XEeG7krDSkOzqJg">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_JykU4e0XEeG7krDSkOzqJg" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_JykU4u0XEeG7krDSkOzqJg" points="[0, 0, -177, 1]$[177, -1, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_Jys3wO0XEeG7krDSkOzqJg" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_JyuF4O0XEeG7krDSkOzqJg" id="port"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
