/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.wisag.automation.micas.olt.device.validation;

import org.eclipse.emf.common.util.EList;

import de.wisag.automation.micas.hwmodules.HardwareAlias;
import de.wisag.automation.micas.hwmodules.HardwareType;
import de.wisag.automation.micas.olt.device.Address;
import de.wisag.automation.micas.olt.device.DeviceInfo;

/**
 * A sample validator interface for
 * {@link de.wisag.automation.micas.olt.device.DeviceInfo}. This doesn't really
 * do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DeviceInfoValidator {
    boolean validate();

    boolean validateModuleName(String value);

    boolean validateVersion(String value);

    boolean validateSerial(String value);

    boolean validateMacAddress(String value);

    boolean validateIpV4Address(String value);

    boolean validateIpV4Netmask(String value);

    boolean validateHardwareType(HardwareType value);

    boolean validateProcessImageAddress(Address value);

    boolean validateFieldBus(int value);

    boolean validateSlaves(EList<DeviceInfo> value);

    boolean validateRawText(String value);

    boolean validateHardwareAlias(HardwareAlias value);
}
