/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.wisag.automation.micas.olt.monitor.validation;

import java.math.BigDecimal;

import de.wisag.automation.micas.rt.RtSymbol;

/**
 * A sample validator interface for
 * {@link de.wisag.automation.micas.olt.monitor.MonitoredValue}. This doesn't
 * really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MonitoredValueValidator {
    boolean validate();

    boolean validateName(String value);

    boolean validateValue(String value);

    boolean validateRtSymbol(RtSymbol value);

    boolean validateValue(BigDecimal value);
}
