/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.wisag.automation.micas.olt.monitor.validation;

import de.wisag.automation.micas.olt.monitor.MonitorModel;
import de.wisag.automation.micas.rt.RtSymbol;

/**
 * A sample validator interface for
 * {@link de.wisag.automation.micas.olt.monitor.MonitoredItem}. This doesn't
 * really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MonitoredItemValidator {
    boolean validate();

    boolean validateIndex(int value);

    boolean validateRtSymbol(RtSymbol value);

    boolean validateTextValue(String value);

    boolean validateMonitorModel(MonitorModel value);
}
