<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dml="http://www.eclipselabs.org/damos/DML/1.0.0" xmlns:dmlnotation="http://www.eclipselabs.org/damos/DMLNotation/1.0.0" xmlns:module="http://www.wisag.de/Automation/Micas/Module" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation">
  <module:Module xmi:id="_kzfGcQUwEeCZzYMl_L3sAw" processor="sss" examiner="rwes" name="test">
    <attributes xsi:type="module:ConstantAttribute" xmi:id="_kzfGcgUwEeCZzYMl_L3sAw" name="enable" dataType="Word">
      <value xsi:type="module:WordValue" xmi:id="_kzfGcwUwEeCZzYMl_L3sAw" value="1"/>
    </attributes>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_kzfGdAUwEeCZzYMl_L3sAw" name="melien" dataType="Reference" row="30" column="0" referenceType="FgaMessageConst"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_kzfGdQUwEeCZzYMl_L3sAw" name="melaus" dataType="Reference" row="31" column="0" referenceType="FgaMessageConst"/>
    <attributes xsi:type="module:VariableAttribute" xmi:id="_kzfGdgUwEeCZzYMl_L3sAw" name="$M0" dataType="Word"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_kzfGdwUwEeCZzYMl_L3sAw" name="anein" dataType="Reference" row="20" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:ReferenceAttribute" xmi:id="_kzfGeAUwEeCZzYMl_L3sAw" name="anaus" dataType="Reference" row="21" referenceType="FgaAnalogValue"/>
    <attributes xsi:type="module:VariableAttribute" xmi:id="_kzftgAUwEeCZzYMl_L3sAw" name="$M1" dataType="Word"/>
    <attributes xsi:type="module:VariableAttribute" xmi:id="_kzftgQUwEeCZzYMl_L3sAw" name="$M2" dataType="Reference"/>
    <attributes xsi:type="module:VariableAttribute" xmi:id="_kzftggUwEeCZzYMl_L3sAw" name="$M4"/>
    <attributes xsi:type="module:VariableAttribute" xmi:id="_kzftgwUwEeCZzYMl_L3sAw" name="$M5"/>
    <tasks xmi:id="_kzfthAUwEeCZzYMl_L3sAw" index="1" name="init"/>
    <tasks xmi:id="_kzfthQUwEeCZzYMl_L3sAw" kind="CYCLIC" cycleTime="550" index="2" name="run">
      <pages xmi:id="_kzfthgUwEeCZzYMl_L3sAw" name="Seite 1">
        <fragmentElements xsi:type="dml:Block" xmi:id="_kzfthwUwEeCZzYMl_L3sAw" name="SETMEL">
          <inputs xsi:type="dml:BlockInput" xmi:id="_kzftiAUwEeCZzYMl_L3sAw">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_kzftiQUwEeCZzYMl_L3sAw"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/SETMEL.blocktype.dml#_j_On4IsyEd-AFYnRH2VIEQ"/>
          </inputs>
          <inputs xsi:type="dml:BlockInput" xmi:id="_kzftigUwEeCZzYMl_L3sAw">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_kzftiwUwEeCZzYMl_L3sAw"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/SETMEL.blocktype.dml#_U8SBYJdMEd-YKM09ARBjYA"/>
          </inputs>
          <inputs xsi:type="dml:BlockInput" xmi:id="_kzftjAUwEeCZzYMl_L3sAw">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_kzftjQUwEeCZzYMl_L3sAw"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/SETMEL.blocktype.dml#_ldiNMJdMEd-YKM09ARBjYA"/>
          </inputs>
          <outputs xsi:type="dml:BlockOutput" xmi:id="_kzftjgUwEeCZzYMl_L3sAw">
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_kzftjwUwEeCZzYMl_L3sAw"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/SETMEL.blocktype.dml#_qCsKcJCpEd-AgqF4Izs_FA"/>
          </outputs>
          <arguments xmi:id="_kzftkAUwEeCZzYMl_L3sAw">
            <value xsi:type="dml:ExpressionSpecification" xmi:id="_kzftkQUwEeCZzYMl_L3sAw" expression="7"/>
            <parameter xsi:type="dml:ExpressionParameter" href="http://www.wisag.de/automation/micas/library/1.0.0/Block.category.dml#_-McSwI2PEd-xLIzFfuJVQQ"/>
          </arguments>
          <type href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/SETMEL.blocktype.dml#_bO6BwIsyEd-AFYnRH2VIEQ"/>
        </fragmentElements>
        <fragmentElements xsi:type="module:Reference" xmi:id="_kzftkgUwEeCZzYMl_L3sAw">
          <outputs xmi:id="_kzftkwUwEeCZzYMl_L3sAw">
            <ports xmi:id="_kzftlAUwEeCZzYMl_L3sAw">
              <signal xsi:type="module:AttributeSpecification" xmi:id="_kzgUkAUwEeCZzYMl_L3sAw" attribute="_kzfGdAUwEeCZzYMl_L3sAw"/>
            </ports>
          </outputs>
        </fragmentElements>
        <fragmentElements xsi:type="module:Reference" xmi:id="_kzgUkQUwEeCZzYMl_L3sAw">
          <outputs xmi:id="_kzgUkgUwEeCZzYMl_L3sAw">
            <ports xmi:id="_kzgUkwUwEeCZzYMl_L3sAw">
              <signal xsi:type="module:AttributeSpecification" xmi:id="_kzgUlAUwEeCZzYMl_L3sAw" attribute="_kzfGdQUwEeCZzYMl_L3sAw"/>
            </ports>
          </outputs>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_kzgUlQUwEeCZzYMl_L3sAw" sourcePort="_kzgUkwUwEeCZzYMl_L3sAw" targetPort="_kzftjQUwEeCZzYMl_L3sAw"/>
        <fragmentElements xsi:type="dml:Block" xmi:id="_kzgUlgUwEeCZzYMl_L3sAw" name="MELEIN">
          <inputs xsi:type="dml:BlockInput" xmi:id="_kzgUlwUwEeCZzYMl_L3sAw">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_kzgUmAUwEeCZzYMl_L3sAw"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/MELEIN.blocktype.dml#_j_On4IsyEd-AFYnRH2VIEQ"/>
          </inputs>
          <outputs xsi:type="dml:BlockOutput" xmi:id="_kzgUmQUwEeCZzYMl_L3sAw">
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_kzgUmgUwEeCZzYMl_L3sAw">
              <signal xsi:type="module:AttributeSpecification" xmi:id="_kzgUmwUwEeCZzYMl_L3sAw" attribute="_kzfGdgUwEeCZzYMl_L3sAw"/>
            </ports>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/MELEIN.blocktype.dml#_1eRDga-CEd-BLuEWVmQTyw"/>
          </outputs>
          <outputs xsi:type="dml:BlockOutput" xmi:id="_kzgUnAUwEeCZzYMl_L3sAw">
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_kzgUnQUwEeCZzYMl_L3sAw"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/MELEIN.blocktype.dml#_qCsKcJCpEd-AgqF4Izs_FA"/>
          </outputs>
          <arguments xmi:id="_kzgUngUwEeCZzYMl_L3sAw">
            <value xsi:type="dml:ExpressionSpecification" xmi:id="_kzgUnwUwEeCZzYMl_L3sAw" expression="3"/>
            <parameter xsi:type="dml:ExpressionParameter" href="http://www.wisag.de/automation/micas/library/1.0.0/Block.category.dml#_-McSwI2PEd-xLIzFfuJVQQ"/>
          </arguments>
          <type href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/MELEIN.blocktype.dml#_bO6BwIsyEd-AFYnRH2VIEQ"/>
        </fragmentElements>
        <fragmentElements xsi:type="module:Constant" xmi:id="_kzgUoAUwEeCZzYMl_L3sAw">
          <outputs xmi:id="_kzgUoQUwEeCZzYMl_L3sAw">
            <ports xmi:id="_kzgUogUwEeCZzYMl_L3sAw">
              <signal xsi:type="module:AttributeSpecification" xmi:id="_kzgUowUwEeCZzYMl_L3sAw" attribute="_kzfGcgUwEeCZzYMl_L3sAw"/>
            </ports>
          </outputs>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_kzg7oAUwEeCZzYMl_L3sAw" sourcePort="_kzgUogUwEeCZzYMl_L3sAw" targetPort="_kzftiQUwEeCZzYMl_L3sAw"/>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_kzg7oQUwEeCZzYMl_L3sAw" sourcePort="_kzftlAUwEeCZzYMl_L3sAw" targetPort="_kzgUmAUwEeCZzYMl_L3sAw"/>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_kzg7ogUwEeCZzYMl_L3sAw" sourcePort="_kzgUmgUwEeCZzYMl_L3sAw" targetPort="_kzftiwUwEeCZzYMl_L3sAw"/>
        <fragmentElements xsi:type="dml:Block" xmi:id="_kzg7owUwEeCZzYMl_L3sAw" name="ANEIN">
          <inputs xsi:type="dml:BlockInput" xmi:id="_kzg7pAUwEeCZzYMl_L3sAw">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_kzg7pQUwEeCZzYMl_L3sAw"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/ANEIN.blocktype.dml#_j_On4IsyEd-AFYnRH2VIEQ"/>
          </inputs>
          <outputs xsi:type="dml:BlockOutput" xmi:id="_kzg7pgUwEeCZzYMl_L3sAw">
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_kzg7pwUwEeCZzYMl_L3sAw">
              <signal xsi:type="module:AttributeSpecification" xmi:id="_kzg7qAUwEeCZzYMl_L3sAw" attribute="_kzftgwUwEeCZzYMl_L3sAw"/>
            </ports>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/ANEIN.blocktype.dml#_wYaLEIsyEd-AFYnRH2VIEQ"/>
          </outputs>
          <outputs xsi:type="dml:BlockOutput" xmi:id="_kzg7qQUwEeCZzYMl_L3sAw">
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_kzg7qgUwEeCZzYMl_L3sAw"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/ANEIN.blocktype.dml#_qCsKcJCpEd-AgqF4Izs_FA"/>
          </outputs>
          <arguments xmi:id="_kzg7qwUwEeCZzYMl_L3sAw">
            <value xsi:type="dml:ExpressionSpecification" xmi:id="_kzg7rAUwEeCZzYMl_L3sAw" expression="8"/>
            <parameter xsi:type="dml:ExpressionParameter" href="http://www.wisag.de/automation/micas/library/1.0.0/Block.category.dml#_-McSwI2PEd-xLIzFfuJVQQ"/>
          </arguments>
          <type href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/ANEIN.blocktype.dml#_bO6BwIsyEd-AFYnRH2VIEQ"/>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Block" xmi:id="_kzg7rQUwEeCZzYMl_L3sAw" name="ANAUS">
          <inputs xsi:type="dml:BlockInput" xmi:id="_kzg7rgUwEeCZzYMl_L3sAw">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_kzg7rwUwEeCZzYMl_L3sAw"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/ANAUS.blocktype.dml#_j_On4IsyEd-AFYnRH2VIEQ"/>
          </inputs>
          <inputs xsi:type="dml:BlockInput" xmi:id="_kzg7sAUwEeCZzYMl_L3sAw">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_kzg7sQUwEeCZzYMl_L3sAw"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/ANAUS.blocktype.dml#_Nld2wJdKEd-YKM09ARBjYA"/>
          </inputs>
          <inputs xsi:type="dml:BlockInput" xmi:id="_kzhisAUwEeCZzYMl_L3sAw">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_kzhisQUwEeCZzYMl_L3sAw"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/ANAUS.blocktype.dml#_SBWMMJdKEd-YKM09ARBjYA"/>
          </inputs>
          <outputs xsi:type="dml:BlockOutput" xmi:id="_kzhisgUwEeCZzYMl_L3sAw">
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_kzhiswUwEeCZzYMl_L3sAw"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/ANAUS.blocktype.dml#_qCsKcJCpEd-AgqF4Izs_FA"/>
          </outputs>
          <arguments xmi:id="_kzhitAUwEeCZzYMl_L3sAw">
            <value xsi:type="dml:ExpressionSpecification" xmi:id="_kzhitQUwEeCZzYMl_L3sAw" expression="9"/>
            <parameter xsi:type="dml:ExpressionParameter" href="http://www.wisag.de/automation/micas/library/1.0.0/Block.category.dml#_-McSwI2PEd-xLIzFfuJVQQ"/>
          </arguments>
          <type href="http://www.wisag.de/automation/micas/library/1.0.0/transfer/ANAUS.blocktype.dml#_bO6BwIsyEd-AFYnRH2VIEQ"/>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_kzhitgUwEeCZzYMl_L3sAw" sourcePort="_kzgUogUwEeCZzYMl_L3sAw" targetPort="_kzg7sQUwEeCZzYMl_L3sAw"/>
        <fragmentElements xsi:type="module:Reference" xmi:id="_kzhitwUwEeCZzYMl_L3sAw">
          <outputs xmi:id="_kzhiuAUwEeCZzYMl_L3sAw">
            <ports xmi:id="_kzhiuQUwEeCZzYMl_L3sAw">
              <signal xsi:type="module:AttributeSpecification" xmi:id="_kzhiugUwEeCZzYMl_L3sAw" attribute="_kzfGdwUwEeCZzYMl_L3sAw"/>
            </ports>
          </outputs>
        </fragmentElements>
        <fragmentElements xsi:type="module:Reference" xmi:id="_kzhiuwUwEeCZzYMl_L3sAw">
          <outputs xmi:id="_kzhivAUwEeCZzYMl_L3sAw">
            <ports xmi:id="_kzhivQUwEeCZzYMl_L3sAw">
              <signal xsi:type="module:AttributeSpecification" xmi:id="_kzhivgUwEeCZzYMl_L3sAw" attribute="_kzfGeAUwEeCZzYMl_L3sAw"/>
            </ports>
          </outputs>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_kziJwAUwEeCZzYMl_L3sAw" sourcePort="_kzhiuQUwEeCZzYMl_L3sAw" targetPort="_kzg7pQUwEeCZzYMl_L3sAw"/>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_kziJwQUwEeCZzYMl_L3sAw" sourcePort="_kzhivQUwEeCZzYMl_L3sAw" targetPort="_kzhisQUwEeCZzYMl_L3sAw"/>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_kziJwgUwEeCZzYMl_L3sAw" sourcePort="_kzg7pwUwEeCZzYMl_L3sAw" targetPort="_kzg7rwUwEeCZzYMl_L3sAw"/>
      </pages>
    </tasks>
  </module:Module>
  <notation:Diagram xmi:id="_kziJwwUwEeCZzYMl_L3sAw" element="_kzfthgUwEeCZzYMl_L3sAw" name="Seite 1" measurementUnit="Himetric">
    <children xmi:id="_kziJxAUwEeCZzYMl_L3sAw" element="_kzfthwUwEeCZzYMl_L3sAw">
      <children xmi:id="_kziJxQUwEeCZzYMl_L3sAw" visible="false" type="_blockName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kziJxgUwEeCZzYMl_L3sAw" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kziJxwUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kziJyAUwEeCZzYMl_L3sAw" element="_kzftiQUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kziJyQUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kziJygUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kziw0AUwEeCZzYMl_L3sAw" element="_kzftjQUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kziw0QUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kziw0gUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kziw0wUwEeCZzYMl_L3sAw" element="_kzftjwUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kziw1AUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kziw1QUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kziw1gUwEeCZzYMl_L3sAw" element="_kzftiwUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kziw1wUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kziw2AUwEeCZzYMl_L3sAw"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_kziw2QUwEeCZzYMl_L3sAw" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_kziw2gUwEeCZzYMl_L3sAw" x="24265" y="3376"/>
    </children>
    <children xmi:id="_kziw2wUwEeCZzYMl_L3sAw" element="_kzftkgUwEeCZzYMl_L3sAw">
      <children xmi:id="_kziw3AUwEeCZzYMl_L3sAw" visible="false" type="_blockName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kziw3QUwEeCZzYMl_L3sAw" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kziw3gUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kziw3wUwEeCZzYMl_L3sAw" element="_kzftlAUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kziw4AUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzjX4AUwEeCZzYMl_L3sAw"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_kzjX4QUwEeCZzYMl_L3sAw" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_kzjX4gUwEeCZzYMl_L3sAw" x="633" y="2390"/>
    </children>
    <children xmi:id="_kzjX4wUwEeCZzYMl_L3sAw" element="_kzgUkQUwEeCZzYMl_L3sAw">
      <children xmi:id="_kzjX5AUwEeCZzYMl_L3sAw" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzjX5QUwEeCZzYMl_L3sAw" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzjX5gUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kzjX5wUwEeCZzYMl_L3sAw" element="_kzgUkwUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzjX6AUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzjX6QUwEeCZzYMl_L3sAw"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_kzjX6gUwEeCZzYMl_L3sAw" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_kzjX6wUwEeCZzYMl_L3sAw" x="17513" y="6963"/>
    </children>
    <children xmi:id="_kzjX7AUwEeCZzYMl_L3sAw" element="_kzgUlgUwEeCZzYMl_L3sAw">
      <children xmi:id="_kzjX7QUwEeCZzYMl_L3sAw" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzjX7gUwEeCZzYMl_L3sAw" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzjX7wUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kzjX8AUwEeCZzYMl_L3sAw" element="_kzgUmAUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzj-8AUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzj-8QUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kzj-8gUwEeCZzYMl_L3sAw" element="_kzgUmgUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzj-8wUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzj-9AUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kzj-9QUwEeCZzYMl_L3sAw" element="_kzgUnQUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzj-9gUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzj-9wUwEeCZzYMl_L3sAw"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_kzj--AUwEeCZzYMl_L3sAw" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_kzj--QUwEeCZzYMl_L3sAw" x="5053" y="6541"/>
    </children>
    <children xmi:id="_kzj--gUwEeCZzYMl_L3sAw" element="_kzgUoAUwEeCZzYMl_L3sAw">
      <children xmi:id="_kzj--wUwEeCZzYMl_L3sAw" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzj-_AUwEeCZzYMl_L3sAw" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzj-_QUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kzj-_gUwEeCZzYMl_L3sAw" element="_kzgUogUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzj-_wUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzj_AAUwEeCZzYMl_L3sAw"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_kzj_AQUwEeCZzYMl_L3sAw" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_kzkmAAUwEeCZzYMl_L3sAw" x="633" y="1266"/>
    </children>
    <children xmi:id="_kzkmAQUwEeCZzYMl_L3sAw" element="_kzg7owUwEeCZzYMl_L3sAw">
      <children xmi:id="_kzkmAgUwEeCZzYMl_L3sAw" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzkmAwUwEeCZzYMl_L3sAw" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzkmBAUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kzkmBQUwEeCZzYMl_L3sAw" element="_kzg7pQUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzkmBgUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzkmBwUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kzkmCAUwEeCZzYMl_L3sAw" element="_kzg7pwUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzkmCQUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzkmCgUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kzkmCwUwEeCZzYMl_L3sAw" element="_kzg7qgUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzkmDAUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzkmDQUwEeCZzYMl_L3sAw"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_kzkmDgUwEeCZzYMl_L3sAw" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_kzkmDwUwEeCZzYMl_L3sAw" x="5053" y="9868"/>
    </children>
    <children xmi:id="_kzlNEAUwEeCZzYMl_L3sAw" element="_kzg7rQUwEeCZzYMl_L3sAw">
      <children xmi:id="_kzlNEQUwEeCZzYMl_L3sAw" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzlNEgUwEeCZzYMl_L3sAw" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzlNEwUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kzlNFAUwEeCZzYMl_L3sAw" element="_kzg7rwUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzlNFQUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzlNFgUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kzlNFwUwEeCZzYMl_L3sAw" element="_kzg7sQUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzlNGAUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzlNGQUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kzlNGgUwEeCZzYMl_L3sAw" element="_kzhisQUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzlNGwUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzlNHAUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kzlNHQUwEeCZzYMl_L3sAw" element="_kzhiswUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzlNHgUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzlNHwUwEeCZzYMl_L3sAw"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_kzlNIAUwEeCZzYMl_L3sAw" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_kzl0IAUwEeCZzYMl_L3sAw" x="19623" y="9868"/>
    </children>
    <children xmi:id="_kzl0IQUwEeCZzYMl_L3sAw" element="_kzhitwUwEeCZzYMl_L3sAw">
      <children xmi:id="_kzl0IgUwEeCZzYMl_L3sAw" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzl0IwUwEeCZzYMl_L3sAw" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzl0JAUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kzl0JQUwEeCZzYMl_L3sAw" element="_kzhiuQUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzl0JgUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzl0JwUwEeCZzYMl_L3sAw"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_kzl0KAUwEeCZzYMl_L3sAw" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_kzl0KQUwEeCZzYMl_L3sAw" x="900" y="10328"/>
    </children>
    <children xmi:id="_kzl0KgUwEeCZzYMl_L3sAw" element="_kzhiuwUwEeCZzYMl_L3sAw">
      <children xmi:id="_kzl0KwUwEeCZzYMl_L3sAw" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzl0LAUwEeCZzYMl_L3sAw" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzl0LQUwEeCZzYMl_L3sAw"/>
      </children>
      <children xmi:id="_kzl0LgUwEeCZzYMl_L3sAw" element="_kzhivQUwEeCZzYMl_L3sAw">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_kzl0LwUwEeCZzYMl_L3sAw" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_kzl0MAUwEeCZzYMl_L3sAw"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_kzl0MQUwEeCZzYMl_L3sAw" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_kzmbMAUwEeCZzYMl_L3sAw" x="8862" y="11320"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_kzmbMQUwEeCZzYMl_L3sAw"/>
    <edges xmi:id="_kzmbMgUwEeCZzYMl_L3sAw" element="_kzgUlQUwEeCZzYMl_L3sAw" source="_kzjX5wUwEeCZzYMl_L3sAw" target="_kziw0AUwEeCZzYMl_L3sAw">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_kzmbMwUwEeCZzYMl_L3sAw" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_kzmbNAUwEeCZzYMl_L3sAw" points="[0, 0, -128, 67]$[128, -67, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_kzmbNQUwEeCZzYMl_L3sAw" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_kzmbNgUwEeCZzYMl_L3sAw" id="port"/>
    </edges>
    <edges xmi:id="_kzmbNwUwEeCZzYMl_L3sAw" element="_kzg7oAUwEeCZzYMl_L3sAw" source="_kzj-_gUwEeCZzYMl_L3sAw" target="_kziJyAUwEeCZzYMl_L3sAw">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_kzmbOAUwEeCZzYMl_L3sAw" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_kzmbOQUwEeCZzYMl_L3sAw" points="[0, 0, 19, -83]$[-19, 83, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_kzmbOgUwEeCZzYMl_L3sAw" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_kzmbOwUwEeCZzYMl_L3sAw" id="port"/>
    </edges>
    <edges xmi:id="_kznCQAUwEeCZzYMl_L3sAw" element="_kzg7oQUwEeCZzYMl_L3sAw" source="_kziw3wUwEeCZzYMl_L3sAw" target="_kzjX8AUwEeCZzYMl_L3sAw">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_kznCQQUwEeCZzYMl_L3sAw" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_kznCQgUwEeCZzYMl_L3sAw" points="[0, 0, -77, 97]$[77, -97, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_kznCQwUwEeCZzYMl_L3sAw" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_kznCRAUwEeCZzYMl_L3sAw" id="port"/>
    </edges>
    <edges xmi:id="_kznCRQUwEeCZzYMl_L3sAw" element="_kzg7ogUwEeCZzYMl_L3sAw" source="_kzj-8gUwEeCZzYMl_L3sAw" target="_kziw1gUwEeCZzYMl_L3sAw">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_kznCRgUwEeCZzYMl_L3sAw" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_kznCRwUwEeCZzYMl_L3sAw" points="[0, 0, -132, -78]$[132, 78, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_kznCSAUwEeCZzYMl_L3sAw" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_kznCSQUwEeCZzYMl_L3sAw" id="port"/>
    </edges>
    <edges xmi:id="_kznCSgUwEeCZzYMl_L3sAw" element="_kzhitgUwEeCZzYMl_L3sAw" source="_kzj-_gUwEeCZzYMl_L3sAw" target="_kzlNFwUwEeCZzYMl_L3sAw">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_kznCSwUwEeCZzYMl_L3sAw" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_kznCTAUwEeCZzYMl_L3sAw" points="[0, 0, -17626, -9571]$[8506, 0, -9120, -9571]$[8506, 9571, -9120, 0]$[17626, 9571, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_kznCTQUwEeCZzYMl_L3sAw" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_kznCTgUwEeCZzYMl_L3sAw" id="port"/>
    </edges>
    <edges xmi:id="_kznCTwUwEeCZzYMl_L3sAw" element="_kziJwAUwEeCZzYMl_L3sAw" source="_kzl0JQUwEeCZzYMl_L3sAw" target="_kzkmBQUwEeCZzYMl_L3sAw">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_kznCUAUwEeCZzYMl_L3sAw" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_kznpUAUwEeCZzYMl_L3sAw" points="[0, 0, -103, 5]$[103, -5, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_kznpUQUwEeCZzYMl_L3sAw" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_kznpUgUwEeCZzYMl_L3sAw" id="port"/>
    </edges>
    <edges xmi:id="_kznpUwUwEeCZzYMl_L3sAw" element="_kziJwQUwEeCZzYMl_L3sAw" source="_kzl0LgUwEeCZzYMl_L3sAw" target="_kzlNGgUwEeCZzYMl_L3sAw">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_kznpVAUwEeCZzYMl_L3sAw" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_kznpVQUwEeCZzYMl_L3sAw" points="[0, 0, -64, 0]$[64, 0, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_kznpVgUwEeCZzYMl_L3sAw" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_kznpVwUwEeCZzYMl_L3sAw" id="port"/>
    </edges>
    <edges xmi:id="_kznpWAUwEeCZzYMl_L3sAw" element="_kziJwgUwEeCZzYMl_L3sAw" source="_kzkmCAUwEeCZzYMl_L3sAw" target="_kzlNFAUwEeCZzYMl_L3sAw">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_kznpWQUwEeCZzYMl_L3sAw" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_kznpWgUwEeCZzYMl_L3sAw" points="[0, 0, -188, 19]$[188, -19, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_kznpWwUwEeCZzYMl_L3sAw" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_kznpXAUwEeCZzYMl_L3sAw" id="port"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
