<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dml="http://www.eclipselabs.org/damos/DML/1.0.0" xmlns:dmlnotation="http://www.eclipselabs.org/damos/DMLNotation/1.0.0" xmlns:module="http://www.wisag.de/Automation/Micas/Module" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation">
  <module:Module xmi:id="__Pd4MF85EeahVLuy7ykjZA" processor="krm" examiner="krm" createdDate="2016-08-10T22:35:34.323+0200" lastModifiedDate="2016-08-10T22:35:34.323+0200" lastInstallDate="2016-08-10T22:35:34.323+0200" name="&lt;new module>">
    <attributes xsi:type="module:VariableAttribute" xmi:id="_TH40IV86EeahVLuy7ykjZA" name="$M0" dataType="Word"/>
    <attributes xsi:type="module:VariableAttribute" xmi:id="_Ypnscl88EeaO29nrgUSJUQ" name="$M1" dataType="Word"/>
    <tasks xmi:id="_ADUXAF86EeahVLuy7ykjZA" cycleTime="1000" index="1" name="Task_init">
      <pages xmi:id="_Ax8-oF86EeahVLuy7ykjZA" name="Diagramm0">
        <fragmentElements xsi:type="dml:Block" xmi:id="_PmRHgF86EeahVLuy7ykjZA" name="ODR2">
          <inputs xsi:type="dml:BlockInput" xmi:id="_PmRHgl86EeahVLuy7ykjZA">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_PmRHg186EeahVLuy7ykjZA"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/binary/ODR2.blocktype.dml#_j_On4IsyEd-AFYnRH2VIEQ"/>
          </inputs>
          <inputs xsi:type="dml:BlockInput" xmi:id="_PmRHhF86EeahVLuy7ykjZA">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_PmRHhV86EeahVLuy7ykjZA"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/binary/ODR2.blocktype.dml#_sFqjgIsyEd-AFYnRH2VIEQ"/>
          </inputs>
          <outputs xsi:type="dml:BlockOutput" xmi:id="_PmRHhl86EeahVLuy7ykjZA">
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_Pma4gF86EeahVLuy7ykjZA">
              <signal xsi:type="module:AttributeSpecification" xmi:id="_YpnscV88EeaO29nrgUSJUQ" attribute="_Ypnscl88EeaO29nrgUSJUQ"/>
            </ports>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/binary/ODR2.blocktype.dml#_wYaLEIsyEd-AFYnRH2VIEQ"/>
          </outputs>
          <arguments xmi:id="_PmRHgV86EeahVLuy7ykjZA">
            <value xsi:type="dml:ExpressionSpecification" xmi:id="_Pmxd0F86EeahVLuy7ykjZA" expression="1"/>
            <parameter xsi:type="dml:ExpressionParameter" href="http://www.wisag.de/automation/micas/library/1.0.0/Block.category.dml#_-McSwI2PEd-xLIzFfuJVQQ"/>
          </arguments>
          <type href="http://www.wisag.de/automation/micas/library/1.0.0/binary/ODR2.blocktype.dml#_bO6BwIsyEd-AFYnRH2VIEQ"/>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Block" xmi:id="_QJFgsF86EeahVLuy7ykjZA" name="ODR22">
          <inputs xsi:type="dml:BlockInput" xmi:id="_QJFgsl86EeahVLuy7ykjZA">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_QJFgs186EeahVLuy7ykjZA"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/binary/ODR2.blocktype.dml#_j_On4IsyEd-AFYnRH2VIEQ"/>
          </inputs>
          <inputs xsi:type="dml:BlockInput" xmi:id="_QJFgtF86EeahVLuy7ykjZA">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_QJFgtV86EeahVLuy7ykjZA"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/binary/ODR2.blocktype.dml#_sFqjgIsyEd-AFYnRH2VIEQ"/>
          </inputs>
          <outputs xsi:type="dml:BlockOutput" xmi:id="_QJFgtl86EeahVLuy7ykjZA">
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_QJFgt186EeahVLuy7ykjZA"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/binary/ODR2.blocktype.dml#_wYaLEIsyEd-AFYnRH2VIEQ"/>
          </outputs>
          <arguments xmi:id="_QJFgsV86EeahVLuy7ykjZA">
            <value xsi:type="dml:ExpressionSpecification" xmi:id="_QJFguF86EeahVLuy7ykjZA" expression="2"/>
            <parameter xsi:type="dml:ExpressionParameter" href="http://www.wisag.de/automation/micas/library/1.0.0/Block.category.dml#_-McSwI2PEd-xLIzFfuJVQQ"/>
          </arguments>
          <type href="http://www.wisag.de/automation/micas/library/1.0.0/binary/ODR2.blocktype.dml#_bO6BwIsyEd-AFYnRH2VIEQ"/>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Block" xmi:id="_QxoucF86EeahVLuy7ykjZA" name="ODR23">
          <inputs xsi:type="dml:BlockInput" xmi:id="_Qxoucl86EeahVLuy7ykjZA">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_Qxouc186EeahVLuy7ykjZA"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/binary/ODR2.blocktype.dml#_j_On4IsyEd-AFYnRH2VIEQ"/>
          </inputs>
          <inputs xsi:type="dml:BlockInput" xmi:id="_QxoudF86EeahVLuy7ykjZA">
            <ports xsi:type="dml:BlockInputPort" xmi:id="_QxoudV86EeahVLuy7ykjZA"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/binary/ODR2.blocktype.dml#_sFqjgIsyEd-AFYnRH2VIEQ"/>
          </inputs>
          <outputs xsi:type="dml:BlockOutput" xmi:id="_Qxoudl86EeahVLuy7ykjZA">
            <ports xsi:type="dml:BlockOutputPort" xmi:id="_Qxoud186EeahVLuy7ykjZA"/>
            <definition href="http://www.wisag.de/automation/micas/library/1.0.0/binary/ODR2.blocktype.dml#_wYaLEIsyEd-AFYnRH2VIEQ"/>
          </outputs>
          <arguments xmi:id="_QxoucV86EeahVLuy7ykjZA">
            <value xsi:type="dml:ExpressionSpecification" xmi:id="_QxoueF86EeahVLuy7ykjZA" expression="3"/>
            <parameter xsi:type="dml:ExpressionParameter" href="http://www.wisag.de/automation/micas/library/1.0.0/Block.category.dml#_-McSwI2PEd-xLIzFfuJVQQ"/>
          </arguments>
          <type href="http://www.wisag.de/automation/micas/library/1.0.0/binary/ODR2.blocktype.dml#_bO6BwIsyEd-AFYnRH2VIEQ"/>
        </fragmentElements>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_YpnscF88EeaO29nrgUSJUQ" source="_Pma4gF86EeahVLuy7ykjZA" target="_QJFgs186EeahVLuy7ykjZA" sourcePort="_Pma4gF86EeahVLuy7ykjZA" targetPort="_QJFgs186EeahVLuy7ykjZA"/>
        <fragmentElements xsi:type="dml:Connection" xmi:id="_aDjT0F88EeaO29nrgUSJUQ" source="_Pma4gF86EeahVLuy7ykjZA" target="_Qxouc186EeahVLuy7ykjZA" sourcePort="_Pma4gF86EeahVLuy7ykjZA" targetPort="_Qxouc186EeahVLuy7ykjZA"/>
      </pages>
    </tasks>
  </module:Module>
  <notation:Diagram xmi:id="_AydU8F86EeahVLuy7ykjZA" element="_Ax8-oF86EeahVLuy7ykjZA" name="Diagramm0" measurementUnit="Himetric">
    <children xmi:id="_Pmxd0V86EeahVLuy7ykjZA" element="_PmRHgF86EeahVLuy7ykjZA">
      <children xmi:id="_Pmxd1F86EeahVLuy7ykjZA" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_Pmxd1V86EeahVLuy7ykjZA" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_Pmxd1l86EeahVLuy7ykjZA"/>
      </children>
      <children xmi:id="_PnOJwF86EeahVLuy7ykjZA" element="_PmRHg186EeahVLuy7ykjZA">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_PnOJwV86EeahVLuy7ykjZA" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_PnOJwl86EeahVLuy7ykjZA"/>
      </children>
      <children xmi:id="_PnOJw186EeahVLuy7ykjZA" element="_PmRHhV86EeahVLuy7ykjZA">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_PnOJxF86EeahVLuy7ykjZA" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_PnOJxV86EeahVLuy7ykjZA"/>
      </children>
      <children xmi:id="_PnOJxl86EeahVLuy7ykjZA" element="_Pma4gF86EeahVLuy7ykjZA">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_PnOJx186EeahVLuy7ykjZA" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_PnOJyF86EeahVLuy7ykjZA"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_Pmxd0l86EeahVLuy7ykjZA" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_Pmxd0186EeahVLuy7ykjZA" x="2730" y="2582"/>
    </children>
    <children xmi:id="_QJFguV86EeahVLuy7ykjZA" element="_QJFgsF86EeahVLuy7ykjZA">
      <children xmi:id="_QJFgvF86EeahVLuy7ykjZA" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_QJFgvV86EeahVLuy7ykjZA" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_QJFgvl86EeahVLuy7ykjZA"/>
      </children>
      <children xmi:id="_QJPRsF86EeahVLuy7ykjZA" element="_QJFgs186EeahVLuy7ykjZA">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_QJPRsV86EeahVLuy7ykjZA" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_QJPRsl86EeahVLuy7ykjZA"/>
      </children>
      <children xmi:id="_QJPRs186EeahVLuy7ykjZA" element="_QJFgtV86EeahVLuy7ykjZA">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_QJPRtF86EeahVLuy7ykjZA" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_QJPRtV86EeahVLuy7ykjZA"/>
      </children>
      <children xmi:id="_QJPRtl86EeahVLuy7ykjZA" element="_QJFgt186EeahVLuy7ykjZA">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_QJPRt186EeahVLuy7ykjZA" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_QJPRuF86EeahVLuy7ykjZA"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_QJFgul86EeahVLuy7ykjZA" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_QJFgu186EeahVLuy7ykjZA" x="11501" y="2582"/>
    </children>
    <children xmi:id="_QxoueV86EeahVLuy7ykjZA" element="_QxoucF86EeahVLuy7ykjZA">
      <children xmi:id="_QxoufF86EeahVLuy7ykjZA" visible="false" type="_componentName">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_QxoufV86EeahVLuy7ykjZA" fontName="Segoe UI" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_Qxoufl86EeahVLuy7ykjZA"/>
      </children>
      <children xmi:id="_Qxouf186EeahVLuy7ykjZA" element="_Qxouc186EeahVLuy7ykjZA">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_QxougF86EeahVLuy7ykjZA" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_QxougV86EeahVLuy7ykjZA"/>
      </children>
      <children xmi:id="_Qxougl86EeahVLuy7ykjZA" element="_QxoudV86EeahVLuy7ykjZA">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_Qxoug186EeahVLuy7ykjZA" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_QxouhF86EeahVLuy7ykjZA"/>
      </children>
      <children xmi:id="_QxouhV86EeahVLuy7ykjZA" element="_Qxoud186EeahVLuy7ykjZA">
        <styles xsi:type="notation:ShapeStyle" xmi:id="_Qxouhl86EeahVLuy7ykjZA" fontName="Segoe UI" fontHeight="8" lineColor="0"/>
        <layoutConstraint xsi:type="notation:Bounds" xmi:id="_Qxouh186EeahVLuy7ykjZA"/>
      </children>
      <styles xsi:type="notation:ShapeStyle" xmi:id="_Qxouel86EeahVLuy7ykjZA" fontName="Segoe UI" lineColor="0"/>
      <layoutConstraint xsi:type="dmlnotation:ComponentLayoutConstraint" xmi:id="_Qxoue186EeahVLuy7ykjZA" x="10456" y="6074"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_AydU8V86EeahVLuy7ykjZA"/>
    <edges xmi:id="_Ypnsc188EeaO29nrgUSJUQ" element="_YpnscF88EeaO29nrgUSJUQ" source="_PnOJxl86EeahVLuy7ykjZA" target="_QJPRsF86EeahVLuy7ykjZA">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_YpnsdF88EeaO29nrgUSJUQ" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_YpnsdV88EeaO29nrgUSJUQ" points="[0, 0, -365, 0]$[365, 0, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_Ypnsdl88EeaO29nrgUSJUQ" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_YpxdcF88EeaO29nrgUSJUQ" id="port"/>
    </edges>
    <edges xmi:id="_aDjT0V88EeaO29nrgUSJUQ" element="_aDjT0F88EeaO29nrgUSJUQ" source="_PnOJxl86EeahVLuy7ykjZA" target="_Qxouf186EeahVLuy7ykjZA">
      <styles xsi:type="notation:ConnectorStyle" xmi:id="_aDjT0l88EeaO29nrgUSJUQ" routing="Rectilinear" lineColor="0"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_aDjT0188EeaO29nrgUSJUQ" points="[0, 0, -315, -165]$[315, 165, 0, 0]"/>
      <sourceAnchor xsi:type="notation:IdentityAnchor" xmi:id="_aDjT1F88EeaO29nrgUSJUQ" id="port"/>
      <targetAnchor xsi:type="notation:IdentityAnchor" xmi:id="_aDjT1V88EeaO29nrgUSJUQ" id="port"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
