/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.wisag.automation.micas.module.validation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

import de.wisag.automation.micas.module.Attribute;
import de.wisag.automation.micas.module.ModuleKind;
import de.wisag.automation.micas.module.PageFormat;
import de.wisag.automation.micas.module.PageOrientation;
import de.wisag.automation.micas.module.Task;

/**
 * A sample validator interface for
 * {@link de.wisag.automation.micas.module.Module}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModuleValidator {
    boolean validate();

    boolean validateKind(ModuleKind value);

    boolean validateAttributes(EList<Attribute> value);

    boolean validateTasks(EList<Task> value);

    boolean validateProcessor(String value);

    boolean validateExaminer(String value);

    boolean validateCreatedDate(Date value);

    boolean validateLastModifiedDate(Date value);

    boolean validateLastInstallDate(Date value);

    boolean validateName(String value);

    boolean validateQualifier(int value);

    boolean validateLineNumber(int value);

    boolean validateStationNumber(int value);

    boolean validateFieldBusNumber(int value);

    boolean validatePageFormat(PageFormat value);

    boolean validatePageOrientation(PageOrientation value);
}
