/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.wisag.automation.micas.module.validation;

import de.wisag.automation.micas.module.ReferenceType;

/**
 * A sample validator interface for
 * {@link de.wisag.automation.micas.module.ReferenceAttribute}. This doesn't
 * really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReferenceAttributeValidator {
    boolean validate();

    boolean validateRow(int value);

    boolean validateColumn(int value);

    boolean validateReferenceType(ReferenceType value);
}
