/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.wisag.automation.micas.module.validation;

import org.eclipse.emf.common.util.EList;

import de.wisag.automation.micas.module.Module;
import de.wisag.automation.micas.module.Page;
import de.wisag.automation.micas.module.TaskKind;

/**
 * A sample validator interface for
 * {@link de.wisag.automation.micas.module.Task}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TaskValidator {
    boolean validate();

    boolean validateKind(TaskKind value);

    boolean validateCycleTime(int value);

    boolean validateIndex(int value);

    boolean validatePages(EList<Page> value);

    boolean validateModule(Module value);

    boolean validateName(String value);
}
