/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.wisag.automation.micas.rt.validation;

import org.eclipse.emf.common.util.EList;

import de.wisag.automation.micas.rt.RtHeadModule;
import de.wisag.automation.micas.rt.RtHwType;
import de.wisag.automation.micas.rt.RtSymbol;
import de.wisag.automation.micas.rt.RtTask;

/**
 * A sample validator interface for
 * {@link de.wisag.automation.micas.rt.RtModule}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RtModuleValidator {
    boolean validate();

    boolean validateSymbols(EList<RtSymbol> value);

    boolean validateDataSegmentAddress(int value);

    boolean validateTasks(EList<RtTask> value);

    boolean validateStartSegmentAddress(int value);

    boolean validateFirstTaskSegmentAddress(int value);

    boolean validateHeadModuleSegmentAddress(int value);

    boolean validateDataSegmentCheckSum(int value);

    boolean validateWordConstOffset(int value);

    boolean validateFloatConstOffset(int value);

    boolean validateWordVarOffset(int value);

    boolean validateFloatVarOffset(int value);

    boolean validateEndOfFloatVars(int value);

    boolean validateDataSegment(byte[] value);

    boolean validateHwType(RtHwType value);

    boolean validateFieldBus(int value);

    boolean validatePastValuesOffset(int value);

    boolean validatePastValuesLastOffset(int value);

    boolean validateTasksCheckSum(int value);

    boolean validateHeadModul(RtHeadModule value);

    boolean validateHeadModuleSegment(byte[] value);

    boolean validateSourceModificationStamp(long value);

    boolean validateSourceName(String value);

    boolean validateSourceChecksum(String value);

    boolean validateComments(EList<String> value);

    boolean validateStartSegment(byte[] value);

    boolean validateComment(String value);

    boolean validateSourceTimestamp(long value);
}
