/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.wisag.automation.micas.rt.validation;

import org.eclipse.emf.common.util.EList;

import de.wisag.automation.micas.rt.RtSymbolAccess;
import de.wisag.automation.micas.rt.RtTask;

/**
 * A sample validator interface for
 * {@link de.wisag.automation.micas.rt.RtModuleInvocation}. This doesn't really
 * do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RtModuleInvocationValidator {
    boolean validate();

    boolean validateArguments(EList<RtSymbolAccess> value);

    boolean validateTask(RtTask value);

    boolean validateName(String value);

    boolean validateIndex(int value);

    boolean validateOpcode(int value);

    boolean validatePastValuesCount(int value);

    boolean validateRuntime(int value);
}
