/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.wisag.automation.micas.rt.validation;

import de.wisag.automation.micas.hwmodules.PortDataType;

/**
 * A sample validator interface for
 * {@link de.wisag.automation.micas.rt.RtReferenceConstant}. This doesn't really
 * do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RtReferenceConstantValidator {
    boolean validate();

    boolean validateCol(int value);

    boolean validateRow(int value);

    boolean validateType(PortDataType value);
}
