/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.wisag.automation.micas.rt.validation;

import de.wisag.automation.micas.rt.RtModuleInvocation;
import de.wisag.automation.micas.rt.RtSymbol;
import de.wisag.automation.micas.rt.RtSymbolAccessType;

/**
 * A sample validator interface for
 * {@link de.wisag.automation.micas.rt.RtSymbolAccess}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RtSymbolAccessValidator {
    boolean validate();

    boolean validateSymbol(RtSymbol value);

    boolean validateModuleInvocation(RtModuleInvocation value);

    boolean validateType(RtSymbolAccessType value);
}
