/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.wisag.automation.micas.hwmodules.validation;

import org.eclipse.emf.common.util.EList;

import de.wisag.automation.micas.hwmodules.HardwareAlias;
import de.wisag.automation.micas.hwmodules.HardwareType;
import de.wisag.automation.micas.hwmodules.Port;

/**
 * A sample validator interface for
 * {@link de.wisag.automation.micas.hwmodules.ModuleDefinition}. This doesn't
 * really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModuleDefinitionValidator {
    boolean validate();

    boolean validateId(int value);

    boolean validateName(String value);

    boolean validateInputs(EList<Port> value);

    boolean validateOutputs(EList<Port> value);

    boolean validateHardwareTypeBlacklist(EList<HardwareType> value);

    boolean validateRuntime(long value);

    boolean validatePastValueCount(int value);

    boolean validateDisplayName(String value);

    boolean validateDescription(String value);

    boolean validateSupportedByHardware(EList<HardwareAlias> value);
}
