/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.wisag.automation.micas.hwmodules.validation;

import org.eclipse.emf.common.util.EList;

import de.wisag.automation.micas.hwmodules.PortDataType;

/**
 * A sample validator interface for
 * {@link de.wisag.automation.micas.hwmodules.Port}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PortValidator {
    boolean validate();

    boolean validateIndex(int value);

    boolean validateAllowedPortDataTypes(EList<PortDataType> value);

    boolean validateInputPort(boolean value);

    boolean validateName(String value);

    boolean validateDisplayName(String value);

    boolean validateDescription(String value);
}
